# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: akash/take/v1/query.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from akash.proto.google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2
from akash.proto.gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2
from akash.proto.amino import amino_pb2 as amino_dot_amino__pb2
from akash.proto.akash.take.v1 import params_pb2 as akash_dot_take_dot_v1_dot_params__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19\x61kash/take/v1/query.proto\x12\rakash.take.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x14gogoproto/gogo.proto\x1a\x11\x61mino/amino.proto\x1a\x1a\x61kash/take/v1/params.proto\"\x14\n\x12QueryParamsRequest\"G\n\x13QueryParamsResponse\x12\x30\n\x06params\x18\x01 \x01(\x0b\x32\x15.akash.take.v1.ParamsB\t\xc8\xde\x1f\x00\xa8\xe7\xb0*\x01\x32w\n\x05Query\x12n\n\x06Params\x12!.akash.take.v1.QueryParamsRequest\x1a\".akash.take.v1.QueryParamsResponse\"\x1d\x82\xd3\xe4\x93\x02\x17\x12\x15/akash/take/v1/paramsB\x1dZ\x1bpkg.akt.dev/go/node/take/v1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'akash.take.v1.query_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\033pkg.akt.dev/go/node/take/v1'
  _globals['_QUERYPARAMSRESPONSE'].fields_by_name['params']._options = None
  _globals['_QUERYPARAMSRESPONSE'].fields_by_name['params']._serialized_options = b'\310\336\037\000\250\347\260*\001'
  _globals['_QUERY'].methods_by_name['Params']._options = None
  _globals['_QUERY'].methods_by_name['Params']._serialized_options = b'\202\323\344\223\002\027\022\025/akash/take/v1/params'
  _globals['_QUERYPARAMSREQUEST']._serialized_start=143
  _globals['_QUERYPARAMSREQUEST']._serialized_end=163
  _globals['_QUERYPARAMSRESPONSE']._serialized_start=165
  _globals['_QUERYPARAMSRESPONSE']._serialized_end=236
  _globals['_QUERY']._serialized_start=238
  _globals['_QUERY']._serialized_end=357
# @@protoc_insertion_point(module_scope)
