# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from akash.proto.akash.take.v1 import paramsmsg_pb2 as akash_dot_take_dot_v1_dot_paramsmsg__pb2


class MsgStub(object):
    """Msg defines the market Msg service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.UpdateParams = channel.unary_unary(
                '/akash.take.v1.Msg/UpdateParams',
                request_serializer=akash_dot_take_dot_v1_dot_paramsmsg__pb2.MsgUpdateParams.SerializeToString,
                response_deserializer=akash_dot_take_dot_v1_dot_paramsmsg__pb2.MsgUpdateParamsResponse.FromString,
                )


class MsgServicer(object):
    """Msg defines the market Msg service
    """

    def UpdateParams(self, request, context):
        """UpdateParams defines a governance operation for updating the x/market module
        parameters. The authority is hard-coded to the x/gov module account.

        Since: akash v1.0.0
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MsgServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'UpdateParams': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateParams,
                    request_deserializer=akash_dot_take_dot_v1_dot_paramsmsg__pb2.MsgUpdateParams.FromString,
                    response_serializer=akash_dot_take_dot_v1_dot_paramsmsg__pb2.MsgUpdateParamsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'akash.take.v1.Msg', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Msg(object):
    """Msg defines the market Msg service
    """

    @staticmethod
    def UpdateParams(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/akash.take.v1.Msg/UpdateParams',
            akash_dot_take_dot_v1_dot_paramsmsg__pb2.MsgUpdateParams.SerializeToString,
            akash_dot_take_dot_v1_dot_paramsmsg__pb2.MsgUpdateParamsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
