# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ibc/core/commitment/v2/commitment.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\'ibc/core/commitment/v2/commitment.proto\x12\x16ibc.core.commitment.v2\"\x1e\n\nMerklePath\x12\x10\n\x08key_path\x18\x01 \x03(\x0c\x42\x42Z@github.com/cosmos/ibc-go/v10/modules/core/23-commitment/types/v2b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ibc.core.commitment.v2.commitment_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z@github.com/cosmos/ibc-go/v10/modules/core/23-commitment/types/v2'
  _globals['_MERKLEPATH']._serialized_start=67
  _globals['_MERKLEPATH']._serialized_end=97
# @@protoc_insertion_point(module_scope)
