# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cosmos/epochs/v1beta1/genesis.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from akash.proto.gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2
from google.protobuf import duration_pb2 as google_dot_protobuf_dot_duration__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#cosmos/epochs/v1beta1/genesis.proto\x12\x15\x63osmos.epochs.v1beta1\x1a\x14gogoproto/gogo.proto\x1a\x1egoogle/protobuf/duration.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xcf\x02\n\tEpochInfo\x12\x12\n\nidentifier\x18\x01 \x01(\t\x12\x38\n\nstart_time\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.TimestampB\x08\xc8\xde\x1f\x00\x90\xdf\x1f\x01\x12K\n\x08\x64uration\x18\x03 \x01(\x0b\x32\x19.google.protobuf.DurationB\x1e\xc8\xde\x1f\x00\xea\xde\x1f\x12\x64uration,omitempty\x98\xdf\x1f\x01\x12\x15\n\rcurrent_epoch\x18\x04 \x01(\x03\x12\x46\n\x18\x63urrent_epoch_start_time\x18\x05 \x01(\x0b\x32\x1a.google.protobuf.TimestampB\x08\xc8\xde\x1f\x00\x90\xdf\x1f\x01\x12\x1e\n\x16\x65poch_counting_started\x18\x06 \x01(\x08\x12\"\n\x1a\x63urrent_epoch_start_height\x18\x08 \x01(\x03J\x04\x08\x07\x10\x08\"F\n\x0cGenesisState\x12\x36\n\x06\x65pochs\x18\x01 \x03(\x0b\x32 .cosmos.epochs.v1beta1.EpochInfoB\x04\xc8\xde\x1f\x00\x42-Z+github.com/cosmos/cosmos-sdk/x/epochs/typesb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cosmos.epochs.v1beta1.genesis_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z+github.com/cosmos/cosmos-sdk/x/epochs/types'
  _globals['_EPOCHINFO'].fields_by_name['start_time']._options = None
  _globals['_EPOCHINFO'].fields_by_name['start_time']._serialized_options = b'\310\336\037\000\220\337\037\001'
  _globals['_EPOCHINFO'].fields_by_name['duration']._options = None
  _globals['_EPOCHINFO'].fields_by_name['duration']._serialized_options = b'\310\336\037\000\352\336\037\022duration,omitempty\230\337\037\001'
  _globals['_EPOCHINFO'].fields_by_name['current_epoch_start_time']._options = None
  _globals['_EPOCHINFO'].fields_by_name['current_epoch_start_time']._serialized_options = b'\310\336\037\000\220\337\037\001'
  _globals['_GENESISSTATE'].fields_by_name['epochs']._options = None
  _globals['_GENESISSTATE'].fields_by_name['epochs']._serialized_options = b'\310\336\037\000'
  _globals['_EPOCHINFO']._serialized_start=150
  _globals['_EPOCHINFO']._serialized_end=485
  _globals['_GENESISSTATE']._serialized_start=487
  _globals['_GENESISSTATE']._serialized_end=557
# @@protoc_insertion_point(module_scope)
