# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: k8s.io/api/coordination/v1beta1/generated.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from akash.proto.k8s.io.api.coordination.v1 import generated_pb2 as k8s_dot_io_dot_api_dot_coordination_dot_v1_dot_generated__pb2
from akash.proto.k8s.io.apimachinery.pkg.apis.meta.v1 import generated_pb2 as k8s_dot_io_dot_apimachinery_dot_pkg_dot_apis_dot_meta_dot_v1_dot_generated__pb2
from akash.proto.k8s.io.apimachinery.pkg.runtime import generated_pb2 as k8s_dot_io_dot_apimachinery_dot_pkg_dot_runtime_dot_generated__pb2
from akash.proto.k8s.io.apimachinery.pkg.runtime.schema import generated_pb2 as k8s_dot_io_dot_apimachinery_dot_pkg_dot_runtime_dot_schema_dot_generated__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n/k8s.io/api/coordination/v1beta1/generated.proto\x12\x1fk8s.io.api.coordination.v1beta1\x1a*k8s.io/api/coordination/v1/generated.proto\x1a\x34k8s.io/apimachinery/pkg/apis/meta/v1/generated.proto\x1a/k8s.io/apimachinery/pkg/runtime/generated.proto\x1a\x36k8s.io/apimachinery/pkg/runtime/schema/generated.proto\"\x85\x01\n\x05Lease\x12\x42\n\x08metadata\x18\x01 \x01(\x0b\x32\x30.k8s.io.apimachinery.pkg.apis.meta.v1.ObjectMeta\x12\x38\n\x04spec\x18\x02 \x01(\x0b\x32*.k8s.io.api.coordination.v1beta1.LeaseSpec\"\x84\x01\n\tLeaseList\x12@\n\x08metadata\x18\x01 \x01(\x0b\x32..k8s.io.apimachinery.pkg.apis.meta.v1.ListMeta\x12\x35\n\x05items\x18\x02 \x03(\x0b\x32&.k8s.io.api.coordination.v1beta1.Lease\"\x90\x02\n\tLeaseSpec\x12\x16\n\x0eholderIdentity\x18\x01 \x01(\t\x12\x1c\n\x14leaseDurationSeconds\x18\x02 \x01(\x05\x12\x44\n\x0b\x61\x63quireTime\x18\x03 \x01(\x0b\x32/.k8s.io.apimachinery.pkg.apis.meta.v1.MicroTime\x12\x42\n\trenewTime\x18\x04 \x01(\x0b\x32/.k8s.io.apimachinery.pkg.apis.meta.v1.MicroTime\x12\x18\n\x10leaseTransitions\x18\x05 \x01(\x05\x12\x10\n\x08strategy\x18\x06 \x01(\t\x12\x17\n\x0fpreferredHolder\x18\x07 \x01(\tB!Z\x1fk8s.io/api/coordination/v1beta1')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'k8s.io.api.coordination.v1beta1.generated_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\037k8s.io/api/coordination/v1beta1'
  _globals['_LEASE']._serialized_start=288
  _globals['_LEASE']._serialized_end=421
  _globals['_LEASELIST']._serialized_start=424
  _globals['_LEASELIST']._serialized_end=556
  _globals['_LEASESPEC']._serialized_start=559
  _globals['_LEASESPEC']._serialized_end=831
# @@protoc_insertion_point(module_scope)
