# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: akash/audit/v1/audit.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from akash.proto.gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2
from akash.proto.akash.base.attributes.v1 import attribute_pb2 as akash_dot_base_dot_attributes_dot_v1_dot_attribute__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1a\x61kash/audit/v1/audit.proto\x12\x0e\x61kash.audit.v1\x1a\x14gogoproto/gogo.proto\x1a(akash/base/attributes/v1/attribute.proto\"\x84\x02\n\x0f\x41uditedProvider\x12(\n\x05owner\x18\x01 \x01(\tB\x19\xea\xde\x1f\x05owner\xf2\xde\x1f\x0cyaml:\"owner\"\x12.\n\x07\x61uditor\x18\x02 \x01(\tB\x1d\xea\xde\x1f\x07\x61uditor\xf2\xde\x1f\x0eyaml:\"auditor\"\x12\x96\x01\n\nattributes\x18\x04 \x03(\x0b\x32#.akash.base.attributes.v1.AttributeB]\xc8\xde\x1f\x00\xea\xde\x1f\nattributes\xf2\xde\x1f\x11yaml:\"attributes\"\xaa\xdf\x1f\x32pkg.akt.dev/go/node/types/attributes/v1.Attributes\"\xb7\x01\n\x16\x41uditedAttributesStore\x12\x96\x01\n\nattributes\x18\x01 \x03(\x0b\x32#.akash.base.attributes.v1.AttributeB]\xc8\xde\x1f\x00\xea\xde\x1f\nattributes\xf2\xde\x1f\x11yaml:\"attributes\"\xaa\xdf\x1f\x32pkg.akt.dev/go/node/types/attributes/v1.Attributes:\x04\xe8\xa0\x1f\x00\"y\n\x11\x41ttributesFilters\x12\x31\n\x08\x61uditors\x18\x01 \x03(\tB\x1f\xea\xde\x1f\x08\x61uditors\xf2\xde\x1f\x0fyaml:\"auditors\"\x12+\n\x06owners\x18\x02 \x03(\tB\x1b\xea\xde\x1f\x06owners\xf2\xde\x1f\ryaml:\"owners\":\x04\xe8\xa0\x1f\x00\x42\x1eZ\x1cpkg.akt.dev/go/node/audit/v1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'akash.audit.v1.audit_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\034pkg.akt.dev/go/node/audit/v1'
  _globals['_AUDITEDPROVIDER'].fields_by_name['owner']._options = None
  _globals['_AUDITEDPROVIDER'].fields_by_name['owner']._serialized_options = b'\352\336\037\005owner\362\336\037\014yaml:\"owner\"'
  _globals['_AUDITEDPROVIDER'].fields_by_name['auditor']._options = None
  _globals['_AUDITEDPROVIDER'].fields_by_name['auditor']._serialized_options = b'\352\336\037\007auditor\362\336\037\016yaml:\"auditor\"'
  _globals['_AUDITEDPROVIDER'].fields_by_name['attributes']._options = None
  _globals['_AUDITEDPROVIDER'].fields_by_name['attributes']._serialized_options = b'\310\336\037\000\352\336\037\nattributes\362\336\037\021yaml:\"attributes\"\252\337\0372pkg.akt.dev/go/node/types/attributes/v1.Attributes'
  _globals['_AUDITEDATTRIBUTESSTORE'].fields_by_name['attributes']._options = None
  _globals['_AUDITEDATTRIBUTESSTORE'].fields_by_name['attributes']._serialized_options = b'\310\336\037\000\352\336\037\nattributes\362\336\037\021yaml:\"attributes\"\252\337\0372pkg.akt.dev/go/node/types/attributes/v1.Attributes'
  _globals['_AUDITEDATTRIBUTESSTORE']._options = None
  _globals['_AUDITEDATTRIBUTESSTORE']._serialized_options = b'\350\240\037\000'
  _globals['_ATTRIBUTESFILTERS'].fields_by_name['auditors']._options = None
  _globals['_ATTRIBUTESFILTERS'].fields_by_name['auditors']._serialized_options = b'\352\336\037\010auditors\362\336\037\017yaml:\"auditors\"'
  _globals['_ATTRIBUTESFILTERS'].fields_by_name['owners']._options = None
  _globals['_ATTRIBUTESFILTERS'].fields_by_name['owners']._serialized_options = b'\352\336\037\006owners\362\336\037\ryaml:\"owners\"'
  _globals['_ATTRIBUTESFILTERS']._options = None
  _globals['_ATTRIBUTESFILTERS']._serialized_options = b'\350\240\037\000'
  _globals['_AUDITEDPROVIDER']._serialized_start=111
  _globals['_AUDITEDPROVIDER']._serialized_end=371
  _globals['_AUDITEDATTRIBUTESSTORE']._serialized_start=374
  _globals['_AUDITEDATTRIBUTESSTORE']._serialized_end=557
  _globals['_ATTRIBUTESFILTERS']._serialized_start=559
  _globals['_ATTRIBUTESFILTERS']._serialized_end=680
# @@protoc_insertion_point(module_scope)
