# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: akash/audit/v1/event.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from akash.proto.gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2
from akash.proto.cosmos_proto import cosmos_pb2 as cosmos__proto_dot_cosmos__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1a\x61kash/audit/v1/event.proto\x12\x0e\x61kash.audit.v1\x1a\x14gogoproto/gogo.proto\x1a\x19\x63osmos_proto/cosmos.proto\"\xac\x01\n\x1a\x45ventTrustedAuditorCreated\x12@\n\x05owner\x18\x01 \x01(\tB1\xea\xde\x1f\x05owner\xf2\xde\x1f\x0cyaml:\"owner\"\xd2\xb4-\x14\x63osmos.AddressString\x12\x46\n\x07\x61uditor\x18\x02 \x01(\tB5\xea\xde\x1f\x07\x61uditor\xf2\xde\x1f\x0eyaml:\"auditor\"\xd2\xb4-\x14\x63osmos.AddressString:\x04\xe8\xa0\x1f\x01\"\xac\x01\n\x1a\x45ventTrustedAuditorDeleted\x12@\n\x05owner\x18\x01 \x01(\tB1\xea\xde\x1f\x05owner\xf2\xde\x1f\x0cyaml:\"owner\"\xd2\xb4-\x14\x63osmos.AddressString\x12\x46\n\x07\x61uditor\x18\x02 \x01(\tB5\xea\xde\x1f\x07\x61uditor\xf2\xde\x1f\x0eyaml:\"auditor\"\xd2\xb4-\x14\x63osmos.AddressString:\x04\xe8\xa0\x1f\x01\x42\x1eZ\x1cpkg.akt.dev/go/node/audit/v1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'akash.audit.v1.event_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\034pkg.akt.dev/go/node/audit/v1'
  _globals['_EVENTTRUSTEDAUDITORCREATED'].fields_by_name['owner']._options = None
  _globals['_EVENTTRUSTEDAUDITORCREATED'].fields_by_name['owner']._serialized_options = b'\352\336\037\005owner\362\336\037\014yaml:\"owner\"\322\264-\024cosmos.AddressString'
  _globals['_EVENTTRUSTEDAUDITORCREATED'].fields_by_name['auditor']._options = None
  _globals['_EVENTTRUSTEDAUDITORCREATED'].fields_by_name['auditor']._serialized_options = b'\352\336\037\007auditor\362\336\037\016yaml:\"auditor\"\322\264-\024cosmos.AddressString'
  _globals['_EVENTTRUSTEDAUDITORCREATED']._options = None
  _globals['_EVENTTRUSTEDAUDITORCREATED']._serialized_options = b'\350\240\037\001'
  _globals['_EVENTTRUSTEDAUDITORDELETED'].fields_by_name['owner']._options = None
  _globals['_EVENTTRUSTEDAUDITORDELETED'].fields_by_name['owner']._serialized_options = b'\352\336\037\005owner\362\336\037\014yaml:\"owner\"\322\264-\024cosmos.AddressString'
  _globals['_EVENTTRUSTEDAUDITORDELETED'].fields_by_name['auditor']._options = None
  _globals['_EVENTTRUSTEDAUDITORDELETED'].fields_by_name['auditor']._serialized_options = b'\352\336\037\007auditor\362\336\037\016yaml:\"auditor\"\322\264-\024cosmos.AddressString'
  _globals['_EVENTTRUSTEDAUDITORDELETED']._options = None
  _globals['_EVENTTRUSTEDAUDITORDELETED']._serialized_options = b'\350\240\037\001'
  _globals['_EVENTTRUSTEDAUDITORCREATED']._serialized_start=96
  _globals['_EVENTTRUSTEDAUDITORCREATED']._serialized_end=268
  _globals['_EVENTTRUSTEDAUDITORDELETED']._serialized_start=271
  _globals['_EVENTTRUSTEDAUDITORDELETED']._serialized_end=443
# @@protoc_insertion_point(module_scope)
