# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: akash/audit/v1/genesis.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from akash.proto.gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2
from akash.proto.akash.audit.v1 import audit_pb2 as akash_dot_audit_dot_v1_dot_audit__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1c\x61kash/audit/v1/genesis.proto\x12\x0e\x61kash.audit.v1\x1a\x14gogoproto/gogo.proto\x1a\x1a\x61kash/audit/v1/audit.proto\"i\n\x0cGenesisState\x12Y\n\tproviders\x18\x01 \x03(\x0b\x32\x1f.akash.audit.v1.AuditedProviderB%\xc8\xde\x1f\x00\xea\xde\x1f\tproviders\xf2\xde\x1f\x10yaml:\"providers\"B\x1eZ\x1cpkg.akt.dev/go/node/audit/v1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'akash.audit.v1.genesis_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\034pkg.akt.dev/go/node/audit/v1'
  _globals['_GENESISSTATE'].fields_by_name['providers']._options = None
  _globals['_GENESISSTATE'].fields_by_name['providers']._serialized_options = b'\310\336\037\000\352\336\037\tproviders\362\336\037\020yaml:\"providers\"'
  _globals['_GENESISSTATE']._serialized_start=98
  _globals['_GENESISSTATE']._serialized_end=203
# @@protoc_insertion_point(module_scope)
