# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: akash/audit/v1/service.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from akash.proto.cosmos.msg.v1 import msg_pb2 as cosmos_dot_msg_dot_v1_dot_msg__pb2
from akash.proto.akash.audit.v1 import msg_pb2 as akash_dot_audit_dot_v1_dot_msg__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1c\x61kash/audit/v1/service.proto\x12\x0e\x61kash.audit.v1\x1a\x17\x63osmos/msg/v1/msg.proto\x1a\x18\x61kash/audit/v1/msg.proto2\x82\x02\n\x03Msg\x12v\n\x16SignProviderAttributes\x12).akash.audit.v1.MsgSignProviderAttributes\x1a\x31.akash.audit.v1.MsgSignProviderAttributesResponse\x12|\n\x18\x44\x65leteProviderAttributes\x12+.akash.audit.v1.MsgDeleteProviderAttributes\x1a\x33.akash.audit.v1.MsgDeleteProviderAttributesResponse\x1a\x05\x80\xe7\xb0*\x01\x42\x1eZ\x1cpkg.akt.dev/go/node/audit/v1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'akash.audit.v1.service_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\034pkg.akt.dev/go/node/audit/v1'
  _globals['_MSG']._options = None
  _globals['_MSG']._serialized_options = b'\200\347\260*\001'
  _globals['_MSG']._serialized_start=100
  _globals['_MSG']._serialized_end=358
# @@protoc_insertion_point(module_scope)
