# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ibc/core/client/v2/query.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from akash.proto.ibc.core.client.v2 import counterparty_pb2 as ibc_dot_core_dot_client_dot_v2_dot_counterparty__pb2
from akash.proto.ibc.core.client.v2 import config_pb2 as ibc_dot_core_dot_client_dot_v2_dot_config__pb2
from akash.proto.google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1eibc/core/client/v2/query.proto\x12\x12ibc.core.client.v2\x1a%ibc/core/client/v2/counterparty.proto\x1a\x1fibc/core/client/v2/config.proto\x1a\x1cgoogle/api/annotations.proto\"1\n\x1cQueryCounterpartyInfoRequest\x12\x11\n\tclient_id\x18\x01 \x01(\t\"`\n\x1dQueryCounterpartyInfoResponse\x12?\n\x11\x63ounterparty_info\x18\x01 \x01(\x0b\x32$.ibc.core.client.v2.CounterpartyInfo\"\'\n\x12QueryConfigRequest\x12\x11\n\tclient_id\x18\x01 \x01(\t\"A\n\x13QueryConfigResponse\x12*\n\x06\x63onfig\x18\x01 \x01(\x0b\x32\x1a.ibc.core.client.v2.Config2\xc8\x02\n\x05Query\x12\xb2\x01\n\x10\x43ounterpartyInfo\x12\x30.ibc.core.client.v2.QueryCounterpartyInfoRequest\x1a\x31.ibc.core.client.v2.QueryCounterpartyInfoResponse\"9\x82\xd3\xe4\x93\x02\x33\x12\x31/ibc/core/client/v2/counterparty_info/{client_id}\x12\x89\x01\n\x06\x43onfig\x12&.ibc.core.client.v2.QueryConfigRequest\x1a\'.ibc.core.client.v2.QueryConfigResponse\".\x82\xd3\xe4\x93\x02(\x12&/ibc/core/client/v2/config/{client_id}B>Z<github.com/cosmos/ibc-go/v10/modules/core/02-client/v2/typesb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ibc.core.client.v2.query_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z<github.com/cosmos/ibc-go/v10/modules/core/02-client/v2/types'
  _globals['_QUERY'].methods_by_name['CounterpartyInfo']._options = None
  _globals['_QUERY'].methods_by_name['CounterpartyInfo']._serialized_options = b'\202\323\344\223\0023\0221/ibc/core/client/v2/counterparty_info/{client_id}'
  _globals['_QUERY'].methods_by_name['Config']._options = None
  _globals['_QUERY'].methods_by_name['Config']._serialized_options = b'\202\323\344\223\002(\022&/ibc/core/client/v2/config/{client_id}'
  _globals['_QUERYCOUNTERPARTYINFOREQUEST']._serialized_start=156
  _globals['_QUERYCOUNTERPARTYINFOREQUEST']._serialized_end=205
  _globals['_QUERYCOUNTERPARTYINFORESPONSE']._serialized_start=207
  _globals['_QUERYCOUNTERPARTYINFORESPONSE']._serialized_end=303
  _globals['_QUERYCONFIGREQUEST']._serialized_start=305
  _globals['_QUERYCONFIGREQUEST']._serialized_end=344
  _globals['_QUERYCONFIGRESPONSE']._serialized_start=346
  _globals['_QUERYCONFIGRESPONSE']._serialized_end=411
  _globals['_QUERY']._serialized_start=414
  _globals['_QUERY']._serialized_end=742
# @@protoc_insertion_point(module_scope)
