# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: akash/base/offchain/sign/v1/sign.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from akash.proto.gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2
from akash.proto.cosmos_proto import cosmos_pb2 as cosmos__proto_dot_cosmos__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&akash/base/offchain/sign/v1/sign.proto\x12\x1b\x61kash.base.offchain.sign.v1\x1a\x14gogoproto/gogo.proto\x1a\x19\x63osmos_proto/cosmos.proto\"j\n\x0bMsgSignData\x12\x43\n\x06signer\x18\x01 \x01(\tB3\xea\xde\x1f\x06signer\xf2\xde\x1f\ryaml:\"signer\"\xd2\xb4-\x14\x63osmos.AddressString\x12\x16\n\x04\x64\x61ta\x18\x02 \x01(\x0c\x42\x08\xea\xde\x1f\x04\x64\x61taB)Z\'pkg.akt.dev/go/node/types/offchain/signb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'akash.base.offchain.sign.v1.sign_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\'pkg.akt.dev/go/node/types/offchain/sign'
  _globals['_MSGSIGNDATA'].fields_by_name['signer']._options = None
  _globals['_MSGSIGNDATA'].fields_by_name['signer']._serialized_options = b'\352\336\037\006signer\362\336\037\ryaml:\"signer\"\322\264-\024cosmos.AddressString'
  _globals['_MSGSIGNDATA'].fields_by_name['data']._options = None
  _globals['_MSGSIGNDATA'].fields_by_name['data']._serialized_options = b'\352\336\037\004data'
  _globals['_MSGSIGNDATA']._serialized_start=120
  _globals['_MSGSIGNDATA']._serialized_end=226
# @@protoc_insertion_point(module_scope)
