# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: akash/market/v1/types.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from akash.proto.gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1b\x61kash/market/v1/types.proto\x12\x0f\x61kash.market.v1\x1a\x14gogoproto/gogo.proto*\x82\x04\n\x11LeaseClosedReason\x12\x36\n\x14lease_closed_invalid\x10\x00\x1a\x1c\x8a\x9d \x18LeaseClosedReasonInvalid\x12\x32\n\x12lease_closed_owner\x10\x01\x1a\x1a\x8a\x9d \x16LeaseClosedReasonOwner\x12@\n\x1clease_closed_reason_unstable\x10\x90N\x1a\x1d\x8a\x9d \x19LeaseClosedReasonUnstable\x12J\n lease_closed_reason_decommission\x10\x91N\x1a#\x8a\x9d \x1fLeaseClosedReasonDecommissioned\x12\x46\n\x1flease_closed_reason_unspecified\x10\x92N\x1a \x8a\x9d \x1cLeaseClosedReasonUnspecified\x12O\n$lease_closed_reason_manifest_timeout\x10\x93N\x1a$\x8a\x9d  LeaseClosedReasonManifestTimeout\x12T\n&lease_closed_reason_insufficient_funds\x10\xa0\x9c\x01\x1a&\x8a\x9d \"LeaseClosedReasonInsufficientFunds\x1a\x04\x88\xa3\x1e\x00\x42\x1fZ\x1dpkg.akt.dev/go/node/market/v1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'akash.market.v1.types_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\035pkg.akt.dev/go/node/market/v1'
  _globals['_LEASECLOSEDREASON']._options = None
  _globals['_LEASECLOSEDREASON']._serialized_options = b'\210\243\036\000'
  _globals['_LEASECLOSEDREASON'].values_by_name["lease_closed_invalid"]._options = None
  _globals['_LEASECLOSEDREASON'].values_by_name["lease_closed_invalid"]._serialized_options = b'\212\235 \030LeaseClosedReasonInvalid'
  _globals['_LEASECLOSEDREASON'].values_by_name["lease_closed_owner"]._options = None
  _globals['_LEASECLOSEDREASON'].values_by_name["lease_closed_owner"]._serialized_options = b'\212\235 \026LeaseClosedReasonOwner'
  _globals['_LEASECLOSEDREASON'].values_by_name["lease_closed_reason_unstable"]._options = None
  _globals['_LEASECLOSEDREASON'].values_by_name["lease_closed_reason_unstable"]._serialized_options = b'\212\235 \031LeaseClosedReasonUnstable'
  _globals['_LEASECLOSEDREASON'].values_by_name["lease_closed_reason_decommission"]._options = None
  _globals['_LEASECLOSEDREASON'].values_by_name["lease_closed_reason_decommission"]._serialized_options = b'\212\235 \037LeaseClosedReasonDecommissioned'
  _globals['_LEASECLOSEDREASON'].values_by_name["lease_closed_reason_unspecified"]._options = None
  _globals['_LEASECLOSEDREASON'].values_by_name["lease_closed_reason_unspecified"]._serialized_options = b'\212\235 \034LeaseClosedReasonUnspecified'
  _globals['_LEASECLOSEDREASON'].values_by_name["lease_closed_reason_manifest_timeout"]._options = None
  _globals['_LEASECLOSEDREASON'].values_by_name["lease_closed_reason_manifest_timeout"]._serialized_options = b'\212\235  LeaseClosedReasonManifestTimeout'
  _globals['_LEASECLOSEDREASON'].values_by_name["lease_closed_reason_insufficient_funds"]._options = None
  _globals['_LEASECLOSEDREASON'].values_by_name["lease_closed_reason_insufficient_funds"]._serialized_options = b'\212\235 \"LeaseClosedReasonInsufficientFunds'
  _globals['_LEASECLOSEDREASON']._serialized_start=71
  _globals['_LEASECLOSEDREASON']._serialized_end=585
# @@protoc_insertion_point(module_scope)
