# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cosmos/counter/v1/query.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1d\x63osmos/counter/v1/query.proto\x12\x11\x63osmos.counter.v1\"\x16\n\x14QueryGetCountRequest\",\n\x15QueryGetCountResponse\x12\x13\n\x0btotal_count\x18\x01 \x01(\x03\x32\x66\n\x05Query\x12]\n\x08GetCount\x12\'.cosmos.counter.v1.QueryGetCountRequest\x1a(.cosmos.counter.v1.QueryGetCountResponseB7Z5github.com/cosmos/cosmos-sdk/testutil/x/counter/typesb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cosmos.counter.v1.query_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z5github.com/cosmos/cosmos-sdk/testutil/x/counter/types'
  _globals['_QUERYGETCOUNTREQUEST']._serialized_start=52
  _globals['_QUERYGETCOUNTREQUEST']._serialized_end=74
  _globals['_QUERYGETCOUNTRESPONSE']._serialized_start=76
  _globals['_QUERYGETCOUNTRESPONSE']._serialized_end=120
  _globals['_QUERY']._serialized_start=122
  _globals['_QUERY']._serialized_end=224
# @@protoc_insertion_point(module_scope)
