# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: akash/market/v1beta5/bid.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from akash.proto.gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2
from akash.proto.cosmos.base.v1beta1 import coin_pb2 as cosmos_dot_base_dot_v1beta1_dot_coin__pb2
from akash.proto.akash.market.v1beta5 import resourcesoffer_pb2 as akash_dot_market_dot_v1beta5_dot_resourcesoffer__pb2
from akash.proto.akash.market.v1 import bid_pb2 as akash_dot_market_dot_v1_dot_bid__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1e\x61kash/market/v1beta5/bid.proto\x12\x14\x61kash.market.v1beta5\x1a\x14gogoproto/gogo.proto\x1a\x1e\x63osmos/base/v1beta1/coin.proto\x1a)akash/market/v1beta5/resourcesoffer.proto\x1a\x19\x61kash/market/v1/bid.proto\"\xcd\x04\n\x03\x42id\x12\x41\n\x02id\x18\x01 \x01(\x0b\x32\x16.akash.market.v1.BidIDB\x1d\xc8\xde\x1f\x00\xe2\xde\x1f\x02ID\xea\xde\x1f\x02id\xf2\xde\x1f\tyaml:\"id\"\x12I\n\x05state\x18\x02 \x01(\x0e\x32\x1f.akash.market.v1beta5.Bid.StateB\x19\xea\xde\x1f\x05state\xf2\xde\x1f\x0cyaml:\"state\"\x12J\n\x05price\x18\x03 \x01(\x0b\x32\x1c.cosmos.base.v1beta1.DecCoinB\x1d\xc8\xde\x1f\x00\xea\xde\x1f\x05price\xf2\xde\x1f\x0cyaml:\"price\"\x12\x36\n\ncreated_at\x18\x04 \x01(\x03\x42\"\xea\xde\x1f\tcreatedAt\xf2\xde\x1f\x11yaml:\"created_at\"\x12\x93\x01\n\x0fresources_offer\x18\x05 \x03(\x0b\x32#.akash.market.v1beta5.ResourceOfferBU\xc8\xde\x1f\x00\xe2\xde\x1f\x0eResourcesOffer\xea\xde\x1f\x0fresources_offer\xf2\xde\x1f\x16yaml:\"resources_offer\"\xaa\xdf\x1f\x0eResourcesOffer\"\x93\x01\n\x05State\x12 \n\x07invalid\x10\x00\x1a\x13\x8a\x9d \x0f\x42idStateInvalid\x12\x15\n\x04open\x10\x01\x1a\x0b\x8a\x9d \x07\x42idOpen\x12\x19\n\x06\x61\x63tive\x10\x02\x1a\r\x8a\x9d \tBidActive\x12\x15\n\x04lost\x10\x03\x1a\x0b\x8a\x9d \x07\x42idLost\x12\x19\n\x06\x63losed\x10\x04\x1a\r\x8a\x9d \tBidClosed\x1a\x04\x88\xa3\x1e\x00:\x08\x98\xa0\x1f\x00\xe8\xa0\x1f\x01\x42$Z\"pkg.akt.dev/go/node/market/v1beta5b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'akash.market.v1beta5.bid_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\"pkg.akt.dev/go/node/market/v1beta5'
  _globals['_BID_STATE']._options = None
  _globals['_BID_STATE']._serialized_options = b'\210\243\036\000'
  _globals['_BID_STATE'].values_by_name["invalid"]._options = None
  _globals['_BID_STATE'].values_by_name["invalid"]._serialized_options = b'\212\235 \017BidStateInvalid'
  _globals['_BID_STATE'].values_by_name["open"]._options = None
  _globals['_BID_STATE'].values_by_name["open"]._serialized_options = b'\212\235 \007BidOpen'
  _globals['_BID_STATE'].values_by_name["active"]._options = None
  _globals['_BID_STATE'].values_by_name["active"]._serialized_options = b'\212\235 \tBidActive'
  _globals['_BID_STATE'].values_by_name["lost"]._options = None
  _globals['_BID_STATE'].values_by_name["lost"]._serialized_options = b'\212\235 \007BidLost'
  _globals['_BID_STATE'].values_by_name["closed"]._options = None
  _globals['_BID_STATE'].values_by_name["closed"]._serialized_options = b'\212\235 \tBidClosed'
  _globals['_BID'].fields_by_name['id']._options = None
  _globals['_BID'].fields_by_name['id']._serialized_options = b'\310\336\037\000\342\336\037\002ID\352\336\037\002id\362\336\037\tyaml:\"id\"'
  _globals['_BID'].fields_by_name['state']._options = None
  _globals['_BID'].fields_by_name['state']._serialized_options = b'\352\336\037\005state\362\336\037\014yaml:\"state\"'
  _globals['_BID'].fields_by_name['price']._options = None
  _globals['_BID'].fields_by_name['price']._serialized_options = b'\310\336\037\000\352\336\037\005price\362\336\037\014yaml:\"price\"'
  _globals['_BID'].fields_by_name['created_at']._options = None
  _globals['_BID'].fields_by_name['created_at']._serialized_options = b'\352\336\037\tcreatedAt\362\336\037\021yaml:\"created_at\"'
  _globals['_BID'].fields_by_name['resources_offer']._options = None
  _globals['_BID'].fields_by_name['resources_offer']._serialized_options = b'\310\336\037\000\342\336\037\016ResourcesOffer\352\336\037\017resources_offer\362\336\037\026yaml:\"resources_offer\"\252\337\037\016ResourcesOffer'
  _globals['_BID']._options = None
  _globals['_BID']._serialized_options = b'\230\240\037\000\350\240\037\001'
  _globals['_BID']._serialized_start=181
  _globals['_BID']._serialized_end=770
  _globals['_BID_STATE']._serialized_start=613
  _globals['_BID_STATE']._serialized_end=760
# @@protoc_insertion_point(module_scope)
