# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: akash/market/v1beta5/bidmsg.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from akash.proto.gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2
from akash.proto.cosmos.base.v1beta1 import coin_pb2 as cosmos_dot_base_dot_v1beta1_dot_coin__pb2
from akash.proto.akash.market.v1beta5 import resourcesoffer_pb2 as akash_dot_market_dot_v1beta5_dot_resourcesoffer__pb2
from akash.proto.akash.market.v1 import bid_pb2 as akash_dot_market_dot_v1_dot_bid__pb2
from akash.proto.akash.base.deposit.v1 import deposit_pb2 as akash_dot_base_dot_deposit_dot_v1_dot_deposit__pb2
from akash.proto.akash.market.v1 import types_pb2 as akash_dot_market_dot_v1_dot_types__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!akash/market/v1beta5/bidmsg.proto\x12\x14\x61kash.market.v1beta5\x1a\x14gogoproto/gogo.proto\x1a\x1e\x63osmos/base/v1beta1/coin.proto\x1a)akash/market/v1beta5/resourcesoffer.proto\x1a\x19\x61kash/market/v1/bid.proto\x1a#akash/base/deposit/v1/deposit.proto\x1a\x1b\x61kash/market/v1/types.proto\"\x8d\x03\n\x0cMsgCreateBid\x12\x41\n\x02id\x18\x01 \x01(\x0b\x32\x16.akash.market.v1.BidIDB\x1d\xc8\xde\x1f\x00\xe2\xde\x1f\x02ID\xea\xde\x1f\x02id\xf2\xde\x1f\tyaml:\"id\"\x12J\n\x05price\x18\x02 \x01(\x0b\x32\x1c.cosmos.base.v1beta1.DecCoinB\x1d\xc8\xde\x1f\x00\xea\xde\x1f\x05price\xf2\xde\x1f\x0cyaml:\"price\"\x12R\n\x07\x64\x65posit\x18\x03 \x01(\x0b\x32\x1e.akash.base.deposit.v1.DepositB!\xc8\xde\x1f\x00\xea\xde\x1f\x07\x64\x65posit\xf2\xde\x1f\x0eyaml:\"deposit\"\x12\x93\x01\n\x0fresources_offer\x18\x04 \x03(\x0b\x32#.akash.market.v1beta5.ResourceOfferBU\xc8\xde\x1f\x00\xe2\xde\x1f\x0eResourcesOffer\xea\xde\x1f\x0fresources_offer\xf2\xde\x1f\x16yaml:\"resources_offer\"\xaa\xdf\x1f\x0eResourcesOffer:\x04\xe8\xa0\x1f\x00\"\x16\n\x14MsgCreateBidResponse\"\xa7\x01\n\x0bMsgCloseBid\x12\x41\n\x02id\x18\x01 \x01(\x0b\x32\x16.akash.market.v1.BidIDB\x1d\xc8\xde\x1f\x00\xe2\xde\x1f\x02ID\xea\xde\x1f\x02id\xf2\xde\x1f\tyaml:\"id\"\x12O\n\x06reason\x18\x02 \x01(\x0e\x32\".akash.market.v1.LeaseClosedReasonB\x1b\xea\xde\x1f\x06reason\xf2\xde\x1f\ryaml:\"reason\":\x04\xe8\xa0\x1f\x00\"\x15\n\x13MsgCloseBidResponseB$Z\"pkg.akt.dev/go/node/market/v1beta5b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'akash.market.v1beta5.bidmsg_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\"pkg.akt.dev/go/node/market/v1beta5'
  _globals['_MSGCREATEBID'].fields_by_name['id']._options = None
  _globals['_MSGCREATEBID'].fields_by_name['id']._serialized_options = b'\310\336\037\000\342\336\037\002ID\352\336\037\002id\362\336\037\tyaml:\"id\"'
  _globals['_MSGCREATEBID'].fields_by_name['price']._options = None
  _globals['_MSGCREATEBID'].fields_by_name['price']._serialized_options = b'\310\336\037\000\352\336\037\005price\362\336\037\014yaml:\"price\"'
  _globals['_MSGCREATEBID'].fields_by_name['deposit']._options = None
  _globals['_MSGCREATEBID'].fields_by_name['deposit']._serialized_options = b'\310\336\037\000\352\336\037\007deposit\362\336\037\016yaml:\"deposit\"'
  _globals['_MSGCREATEBID'].fields_by_name['resources_offer']._options = None
  _globals['_MSGCREATEBID'].fields_by_name['resources_offer']._serialized_options = b'\310\336\037\000\342\336\037\016ResourcesOffer\352\336\037\017resources_offer\362\336\037\026yaml:\"resources_offer\"\252\337\037\016ResourcesOffer'
  _globals['_MSGCREATEBID']._options = None
  _globals['_MSGCREATEBID']._serialized_options = b'\350\240\037\000'
  _globals['_MSGCLOSEBID'].fields_by_name['id']._options = None
  _globals['_MSGCLOSEBID'].fields_by_name['id']._serialized_options = b'\310\336\037\000\342\336\037\002ID\352\336\037\002id\362\336\037\tyaml:\"id\"'
  _globals['_MSGCLOSEBID'].fields_by_name['reason']._options = None
  _globals['_MSGCLOSEBID'].fields_by_name['reason']._serialized_options = b'\352\336\037\006reason\362\336\037\ryaml:\"reason\"'
  _globals['_MSGCLOSEBID']._options = None
  _globals['_MSGCLOSEBID']._serialized_options = b'\350\240\037\000'
  _globals['_MSGCREATEBID']._serialized_start=250
  _globals['_MSGCREATEBID']._serialized_end=647
  _globals['_MSGCREATEBIDRESPONSE']._serialized_start=649
  _globals['_MSGCREATEBIDRESPONSE']._serialized_end=671
  _globals['_MSGCLOSEBID']._serialized_start=674
  _globals['_MSGCLOSEBID']._serialized_end=841
  _globals['_MSGCLOSEBIDRESPONSE']._serialized_start=843
  _globals['_MSGCLOSEBIDRESPONSE']._serialized_end=864
# @@protoc_insertion_point(module_scope)
