# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: akash/market/v1beta5/genesis.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from akash.proto.gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2
from akash.proto.akash.market.v1 import lease_pb2 as akash_dot_market_dot_v1_dot_lease__pb2
from akash.proto.akash.market.v1beta5 import params_pb2 as akash_dot_market_dot_v1beta5_dot_params__pb2
from akash.proto.akash.market.v1beta5 import bid_pb2 as akash_dot_market_dot_v1beta5_dot_bid__pb2
from akash.proto.akash.market.v1beta5 import order_pb2 as akash_dot_market_dot_v1beta5_dot_order__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"akash/market/v1beta5/genesis.proto\x12\x14\x61kash.market.v1beta5\x1a\x14gogoproto/gogo.proto\x1a\x1b\x61kash/market/v1/lease.proto\x1a!akash/market/v1beta5/params.proto\x1a\x1e\x61kash/market/v1beta5/bid.proto\x1a akash/market/v1beta5/order.proto\"\xf4\x02\n\x0cGenesisState\x12M\n\x06params\x18\x01 \x01(\x0b\x32\x1c.akash.market.v1beta5.ParamsB\x1f\xc8\xde\x1f\x00\xea\xde\x1f\x06params\xf2\xde\x1f\ryaml:\"params\"\x12V\n\x06orders\x18\x02 \x03(\x0b\x32\x1b.akash.market.v1beta5.OrderB)\xc8\xde\x1f\x00\xea\xde\x1f\x06orders\xf2\xde\x1f\ryaml:\"orders\"\xaa\xdf\x1f\x06Orders\x12o\n\x06leases\x18\x03 \x03(\x0b\x32\x16.akash.market.v1.LeaseBG\xc8\xde\x1f\x00\xea\xde\x1f\x06leases\xf2\xde\x1f\ryaml:\"leases\"\xaa\xdf\x1f$pkg.akt.dev/go/node/market/v1.Leases\x12L\n\x04\x62ids\x18\x04 \x03(\x0b\x32\x19.akash.market.v1beta5.BidB#\xc8\xde\x1f\x00\xea\xde\x1f\x04\x62ids\xf2\xde\x1f\x0byaml:\"bids\"\xaa\xdf\x1f\x04\x42idsB$Z\"pkg.akt.dev/go/node/market/v1beta5b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'akash.market.v1beta5.genesis_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\"pkg.akt.dev/go/node/market/v1beta5'
  _globals['_GENESISSTATE'].fields_by_name['params']._options = None
  _globals['_GENESISSTATE'].fields_by_name['params']._serialized_options = b'\310\336\037\000\352\336\037\006params\362\336\037\ryaml:\"params\"'
  _globals['_GENESISSTATE'].fields_by_name['orders']._options = None
  _globals['_GENESISSTATE'].fields_by_name['orders']._serialized_options = b'\310\336\037\000\352\336\037\006orders\362\336\037\ryaml:\"orders\"\252\337\037\006Orders'
  _globals['_GENESISSTATE'].fields_by_name['leases']._options = None
  _globals['_GENESISSTATE'].fields_by_name['leases']._serialized_options = b'\310\336\037\000\352\336\037\006leases\362\336\037\ryaml:\"leases\"\252\337\037$pkg.akt.dev/go/node/market/v1.Leases'
  _globals['_GENESISSTATE'].fields_by_name['bids']._options = None
  _globals['_GENESISSTATE'].fields_by_name['bids']._serialized_options = b'\310\336\037\000\352\336\037\004bids\362\336\037\013yaml:\"bids\"\252\337\037\004Bids'
  _globals['_GENESISSTATE']._serialized_start=213
  _globals['_GENESISSTATE']._serialized_end=585
# @@protoc_insertion_point(module_scope)
