# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: akash/market/v1beta5/leasemsg.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from akash.proto.gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2
from akash.proto.akash.market.v1 import bid_pb2 as akash_dot_market_dot_v1_dot_bid__pb2
from akash.proto.akash.market.v1 import lease_pb2 as akash_dot_market_dot_v1_dot_lease__pb2
from akash.proto.akash.market.v1 import types_pb2 as akash_dot_market_dot_v1_dot_types__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#akash/market/v1beta5/leasemsg.proto\x12\x14\x61kash.market.v1beta5\x1a\x14gogoproto/gogo.proto\x1a\x19\x61kash/market/v1/bid.proto\x1a\x1b\x61kash/market/v1/lease.proto\x1a\x1b\x61kash/market/v1/types.proto\"`\n\x0eMsgCreateLease\x12H\n\x06\x62id_id\x18\x01 \x01(\x0b\x32\x16.akash.market.v1.BidIDB \xc8\xde\x1f\x00\xe2\xde\x1f\x05\x42idID\xea\xde\x1f\x02id\xf2\xde\x1f\tyaml:\"id\":\x04\xe8\xa0\x1f\x00\"\x18\n\x16MsgCreateLeaseResponse\"]\n\x10MsgWithdrawLease\x12\x43\n\x02id\x18\x01 \x01(\x0b\x32\x18.akash.market.v1.LeaseIDB\x1d\xc8\xde\x1f\x00\xe2\xde\x1f\x02ID\xea\xde\x1f\x02id\xf2\xde\x1f\tyaml:\"id\":\x04\xe8\xa0\x1f\x00\"\x1a\n\x18MsgWithdrawLeaseResponse\"\xab\x01\n\rMsgCloseLease\x12\x43\n\x02id\x18\x01 \x01(\x0b\x32\x18.akash.market.v1.LeaseIDB\x1d\xc8\xde\x1f\x00\xe2\xde\x1f\x02ID\xea\xde\x1f\x02id\xf2\xde\x1f\tyaml:\"id\"\x12O\n\x06reason\x18\x02 \x01(\x0e\x32\".akash.market.v1.LeaseClosedReasonB\x1b\xea\xde\x1f\x06reason\xf2\xde\x1f\ryaml:\"reason\":\x04\xe8\xa0\x1f\x00\"\x17\n\x15MsgCloseLeaseResponseB$Z\"pkg.akt.dev/go/node/market/v1beta5b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'akash.market.v1beta5.leasemsg_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\"pkg.akt.dev/go/node/market/v1beta5'
  _globals['_MSGCREATELEASE'].fields_by_name['bid_id']._options = None
  _globals['_MSGCREATELEASE'].fields_by_name['bid_id']._serialized_options = b'\310\336\037\000\342\336\037\005BidID\352\336\037\002id\362\336\037\tyaml:\"id\"'
  _globals['_MSGCREATELEASE']._options = None
  _globals['_MSGCREATELEASE']._serialized_options = b'\350\240\037\000'
  _globals['_MSGWITHDRAWLEASE'].fields_by_name['id']._options = None
  _globals['_MSGWITHDRAWLEASE'].fields_by_name['id']._serialized_options = b'\310\336\037\000\342\336\037\002ID\352\336\037\002id\362\336\037\tyaml:\"id\"'
  _globals['_MSGWITHDRAWLEASE']._options = None
  _globals['_MSGWITHDRAWLEASE']._serialized_options = b'\350\240\037\000'
  _globals['_MSGCLOSELEASE'].fields_by_name['id']._options = None
  _globals['_MSGCLOSELEASE'].fields_by_name['id']._serialized_options = b'\310\336\037\000\342\336\037\002ID\352\336\037\002id\362\336\037\tyaml:\"id\"'
  _globals['_MSGCLOSELEASE'].fields_by_name['reason']._options = None
  _globals['_MSGCLOSELEASE'].fields_by_name['reason']._serialized_options = b'\352\336\037\006reason\362\336\037\ryaml:\"reason\"'
  _globals['_MSGCLOSELEASE']._options = None
  _globals['_MSGCLOSELEASE']._serialized_options = b'\350\240\037\000'
  _globals['_MSGCREATELEASE']._serialized_start=168
  _globals['_MSGCREATELEASE']._serialized_end=264
  _globals['_MSGCREATELEASERESPONSE']._serialized_start=266
  _globals['_MSGCREATELEASERESPONSE']._serialized_end=290
  _globals['_MSGWITHDRAWLEASE']._serialized_start=292
  _globals['_MSGWITHDRAWLEASE']._serialized_end=385
  _globals['_MSGWITHDRAWLEASERESPONSE']._serialized_start=387
  _globals['_MSGWITHDRAWLEASERESPONSE']._serialized_end=413
  _globals['_MSGCLOSELEASE']._serialized_start=416
  _globals['_MSGCLOSELEASE']._serialized_end=587
  _globals['_MSGCLOSELEASERESPONSE']._serialized_start=589
  _globals['_MSGCLOSELEASERESPONSE']._serialized_end=612
# @@protoc_insertion_point(module_scope)
