# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: akash/market/v1beta5/order.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from akash.proto.gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2
from akash.proto.akash.deployment.v1beta4 import groupspec_pb2 as akash_dot_deployment_dot_v1beta4_dot_groupspec__pb2
from akash.proto.akash.market.v1 import order_pb2 as akash_dot_market_dot_v1_dot_order__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n akash/market/v1beta5/order.proto\x12\x14\x61kash.market.v1beta5\x1a\x14gogoproto/gogo.proto\x1a(akash/deployment/v1beta4/groupspec.proto\x1a\x1b\x61kash/market/v1/order.proto\"\x8e\x03\n\x05Order\x12\x43\n\x02id\x18\x01 \x01(\x0b\x32\x18.akash.market.v1.OrderIDB\x1d\xc8\xde\x1f\x00\xe2\xde\x1f\x02ID\xea\xde\x1f\x02id\xf2\xde\x1f\tyaml:\"id\"\x12K\n\x05state\x18\x02 \x01(\x0e\x32!.akash.market.v1beta5.Order.StateB\x19\xea\xde\x1f\x05state\xf2\xde\x1f\x0cyaml:\"state\"\x12N\n\x04spec\x18\x03 \x01(\x0b\x32#.akash.deployment.v1beta4.GroupSpecB\x1b\xc8\xde\x1f\x00\xea\xde\x1f\x04spec\xf2\xde\x1f\x0byaml:\"spec\"\x12\x12\n\ncreated_at\x18\x04 \x01(\x03\"\x84\x01\n\x05State\x12\"\n\x07invalid\x10\x00\x1a\x15\x8a\x9d \x11OrderStateInvalid\x12\x17\n\x04open\x10\x01\x1a\r\x8a\x9d \tOrderOpen\x12\x1b\n\x06\x61\x63tive\x10\x02\x1a\x0f\x8a\x9d \x0bOrderActive\x12\x1b\n\x06\x63losed\x10\x03\x1a\x0f\x8a\x9d \x0bOrderClosed\x1a\x04\x88\xa3\x1e\x00:\x08\x98\xa0\x1f\x00\xe8\xa0\x1f\x00\x42$Z\"pkg.akt.dev/go/node/market/v1beta5b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'akash.market.v1beta5.order_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\"pkg.akt.dev/go/node/market/v1beta5'
  _globals['_ORDER_STATE']._options = None
  _globals['_ORDER_STATE']._serialized_options = b'\210\243\036\000'
  _globals['_ORDER_STATE'].values_by_name["invalid"]._options = None
  _globals['_ORDER_STATE'].values_by_name["invalid"]._serialized_options = b'\212\235 \021OrderStateInvalid'
  _globals['_ORDER_STATE'].values_by_name["open"]._options = None
  _globals['_ORDER_STATE'].values_by_name["open"]._serialized_options = b'\212\235 \tOrderOpen'
  _globals['_ORDER_STATE'].values_by_name["active"]._options = None
  _globals['_ORDER_STATE'].values_by_name["active"]._serialized_options = b'\212\235 \013OrderActive'
  _globals['_ORDER_STATE'].values_by_name["closed"]._options = None
  _globals['_ORDER_STATE'].values_by_name["closed"]._serialized_options = b'\212\235 \013OrderClosed'
  _globals['_ORDER'].fields_by_name['id']._options = None
  _globals['_ORDER'].fields_by_name['id']._serialized_options = b'\310\336\037\000\342\336\037\002ID\352\336\037\002id\362\336\037\tyaml:\"id\"'
  _globals['_ORDER'].fields_by_name['state']._options = None
  _globals['_ORDER'].fields_by_name['state']._serialized_options = b'\352\336\037\005state\362\336\037\014yaml:\"state\"'
  _globals['_ORDER'].fields_by_name['spec']._options = None
  _globals['_ORDER'].fields_by_name['spec']._serialized_options = b'\310\336\037\000\352\336\037\004spec\362\336\037\013yaml:\"spec\"'
  _globals['_ORDER']._options = None
  _globals['_ORDER']._serialized_options = b'\230\240\037\000\350\240\037\000'
  _globals['_ORDER']._serialized_start=152
  _globals['_ORDER']._serialized_end=550
  _globals['_ORDER_STATE']._serialized_start=408
  _globals['_ORDER_STATE']._serialized_end=540
# @@protoc_insertion_point(module_scope)
