# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: akash/market/v1beta5/resourcesoffer.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from akash.proto.gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2
from akash.proto.akash.base.resources.v1beta4 import resources_pb2 as akash_dot_base_dot_resources_dot_v1beta4_dot_resources__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n)akash/market/v1beta5/resourcesoffer.proto\x12\x14\x61kash.market.v1beta5\x1a\x14gogoproto/gogo.proto\x1a,akash/base/resources/v1beta4/resources.proto\"\xa2\x01\n\rResourceOffer\x12\x61\n\tresources\x18\x01 \x01(\x0b\x32\'.akash.base.resources.v1beta4.ResourcesB%\xc8\xde\x1f\x00\xea\xde\x1f\tresources\xf2\xde\x1f\x10yaml:\"resources\"\x12(\n\x05\x63ount\x18\x02 \x01(\rB\x19\xea\xde\x1f\x05\x63ount\xf2\xde\x1f\x0cyaml:\"count\":\x04\xe8\xa0\x1f\x01\x42$Z\"pkg.akt.dev/go/node/market/v1beta5b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'akash.market.v1beta5.resourcesoffer_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\"pkg.akt.dev/go/node/market/v1beta5'
  _globals['_RESOURCEOFFER'].fields_by_name['resources']._options = None
  _globals['_RESOURCEOFFER'].fields_by_name['resources']._serialized_options = b'\310\336\037\000\352\336\037\tresources\362\336\037\020yaml:\"resources\"'
  _globals['_RESOURCEOFFER'].fields_by_name['count']._options = None
  _globals['_RESOURCEOFFER'].fields_by_name['count']._serialized_options = b'\352\336\037\005count\362\336\037\014yaml:\"count\"'
  _globals['_RESOURCEOFFER']._options = None
  _globals['_RESOURCEOFFER']._serialized_options = b'\350\240\037\001'
  _globals['_RESOURCEOFFER']._serialized_start=136
  _globals['_RESOURCEOFFER']._serialized_end=298
# @@protoc_insertion_point(module_scope)
