# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: akash/market/v1beta5/service.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from akash.proto.akash.market.v1beta5 import bidmsg_pb2 as akash_dot_market_dot_v1beta5_dot_bidmsg__pb2
from akash.proto.akash.market.v1beta5 import leasemsg_pb2 as akash_dot_market_dot_v1beta5_dot_leasemsg__pb2
from akash.proto.akash.market.v1beta5 import paramsmsg_pb2 as akash_dot_market_dot_v1beta5_dot_paramsmsg__pb2
from akash.proto.cosmos.msg.v1 import msg_pb2 as cosmos_dot_msg_dot_v1_dot_msg__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"akash/market/v1beta5/service.proto\x12\x14\x61kash.market.v1beta5\x1a!akash/market/v1beta5/bidmsg.proto\x1a#akash/market/v1beta5/leasemsg.proto\x1a$akash/market/v1beta5/paramsmsg.proto\x1a\x17\x63osmos/msg/v1/msg.proto2\xd5\x04\n\x03Msg\x12[\n\tCreateBid\x12\".akash.market.v1beta5.MsgCreateBid\x1a*.akash.market.v1beta5.MsgCreateBidResponse\x12X\n\x08\x43loseBid\x12!.akash.market.v1beta5.MsgCloseBid\x1a).akash.market.v1beta5.MsgCloseBidResponse\x12g\n\rWithdrawLease\x12&.akash.market.v1beta5.MsgWithdrawLease\x1a..akash.market.v1beta5.MsgWithdrawLeaseResponse\x12\x61\n\x0b\x43reateLease\x12$.akash.market.v1beta5.MsgCreateLease\x1a,.akash.market.v1beta5.MsgCreateLeaseResponse\x12^\n\nCloseLease\x12#.akash.market.v1beta5.MsgCloseLease\x1a+.akash.market.v1beta5.MsgCloseLeaseResponse\x12\x64\n\x0cUpdateParams\x12%.akash.market.v1beta5.MsgUpdateParams\x1a-.akash.market.v1beta5.MsgUpdateParamsResponse\x1a\x05\x80\xe7\xb0*\x01\x42$Z\"pkg.akt.dev/go/node/market/v1beta5b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'akash.market.v1beta5.service_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\"pkg.akt.dev/go/node/market/v1beta5'
  _globals['_MSG']._options = None
  _globals['_MSG']._serialized_options = b'\200\347\260*\001'
  _globals['_MSG']._serialized_start=196
  _globals['_MSG']._serialized_end=793
# @@protoc_insertion_point(module_scope)
