# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: akash/provider/v1beta4/event.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from akash.proto.gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2
from akash.proto.cosmos_proto import cosmos_pb2 as cosmos__proto_dot_cosmos__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"akash/provider/v1beta4/event.proto\x12\x16\x61kash.provider.v1beta4\x1a\x14gogoproto/gogo.proto\x1a\x19\x63osmos_proto/cosmos.proto\"^\n\x14\x45ventProviderCreated\x12@\n\x05owner\x18\x01 \x01(\tB1\xea\xde\x1f\x05owner\xf2\xde\x1f\x0cyaml:\"owner\"\xd2\xb4-\x14\x63osmos.AddressString:\x04\xe8\xa0\x1f\x01\"^\n\x14\x45ventProviderUpdated\x12@\n\x05owner\x18\x01 \x01(\tB1\xea\xde\x1f\x05owner\xf2\xde\x1f\x0cyaml:\"owner\"\xd2\xb4-\x14\x63osmos.AddressString:\x04\xe8\xa0\x1f\x01\"^\n\x14\x45ventProviderDeleted\x12@\n\x05owner\x18\x01 \x01(\tB1\xea\xde\x1f\x05owner\xf2\xde\x1f\x0cyaml:\"owner\"\xd2\xb4-\x14\x63osmos.AddressString:\x04\xe8\xa0\x1f\x01\x42&Z$pkg.akt.dev/go/node/provider/v1beta4b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'akash.provider.v1beta4.event_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z$pkg.akt.dev/go/node/provider/v1beta4'
  _globals['_EVENTPROVIDERCREATED'].fields_by_name['owner']._options = None
  _globals['_EVENTPROVIDERCREATED'].fields_by_name['owner']._serialized_options = b'\352\336\037\005owner\362\336\037\014yaml:\"owner\"\322\264-\024cosmos.AddressString'
  _globals['_EVENTPROVIDERCREATED']._options = None
  _globals['_EVENTPROVIDERCREATED']._serialized_options = b'\350\240\037\001'
  _globals['_EVENTPROVIDERUPDATED'].fields_by_name['owner']._options = None
  _globals['_EVENTPROVIDERUPDATED'].fields_by_name['owner']._serialized_options = b'\352\336\037\005owner\362\336\037\014yaml:\"owner\"\322\264-\024cosmos.AddressString'
  _globals['_EVENTPROVIDERUPDATED']._options = None
  _globals['_EVENTPROVIDERUPDATED']._serialized_options = b'\350\240\037\001'
  _globals['_EVENTPROVIDERDELETED'].fields_by_name['owner']._options = None
  _globals['_EVENTPROVIDERDELETED'].fields_by_name['owner']._serialized_options = b'\352\336\037\005owner\362\336\037\014yaml:\"owner\"\322\264-\024cosmos.AddressString'
  _globals['_EVENTPROVIDERDELETED']._options = None
  _globals['_EVENTPROVIDERDELETED']._serialized_options = b'\350\240\037\001'
  _globals['_EVENTPROVIDERCREATED']._serialized_start=111
  _globals['_EVENTPROVIDERCREATED']._serialized_end=205
  _globals['_EVENTPROVIDERUPDATED']._serialized_start=207
  _globals['_EVENTPROVIDERUPDATED']._serialized_end=301
  _globals['_EVENTPROVIDERDELETED']._serialized_start=303
  _globals['_EVENTPROVIDERDELETED']._serialized_end=397
# @@protoc_insertion_point(module_scope)
