# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: akash/provider/v1beta4/genesis.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from akash.proto.gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2
from akash.proto.akash.provider.v1beta4 import provider_pb2 as akash_dot_provider_dot_v1beta4_dot_provider__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n$akash/provider/v1beta4/genesis.proto\x12\x16\x61kash.provider.v1beta4\x1a\x14gogoproto/gogo.proto\x1a%akash/provider/v1beta4/provider.proto\"w\n\x0cGenesisState\x12g\n\tproviders\x18\x01 \x03(\x0b\x32 .akash.provider.v1beta4.ProviderB2\xc8\xde\x1f\x00\xea\xde\x1f\tproviders\xf2\xde\x1f\x10yaml:\"providers\"\xaa\xdf\x1f\tProvidersB&Z$pkg.akt.dev/go/node/provider/v1beta4b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'akash.provider.v1beta4.genesis_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z$pkg.akt.dev/go/node/provider/v1beta4'
  _globals['_GENESISSTATE'].fields_by_name['providers']._options = None
  _globals['_GENESISSTATE'].fields_by_name['providers']._serialized_options = b'\310\336\037\000\352\336\037\tproviders\362\336\037\020yaml:\"providers\"\252\337\037\tProviders'
  _globals['_GENESISSTATE']._serialized_start=125
  _globals['_GENESISSTATE']._serialized_end=244
# @@protoc_insertion_point(module_scope)
