# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: akash/provider/v1beta4/provider.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from akash.proto.gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2
from akash.proto.cosmos_proto import cosmos_pb2 as cosmos__proto_dot_cosmos__pb2
from akash.proto.akash.base.attributes.v1 import attribute_pb2 as akash_dot_base_dot_attributes_dot_v1_dot_attribute__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n%akash/provider/v1beta4/provider.proto\x12\x16\x61kash.provider.v1beta4\x1a\x14gogoproto/gogo.proto\x1a\x19\x63osmos_proto/cosmos.proto\x1a(akash/base/attributes/v1/attribute.proto\"i\n\x04Info\x12\x31\n\x05\x65mail\x18\x01 \x01(\tB\"\xe2\xde\x1f\x05\x45Mail\xea\xde\x1f\x05\x65mail\xf2\xde\x1f\x0cyaml:\"email\"\x12.\n\x07website\x18\x02 \x01(\tB\x1d\xea\xde\x1f\x07website\xf2\xde\x1f\x0eyaml:\"website\"\"\xf6\x02\n\x08Provider\x12@\n\x05owner\x18\x01 \x01(\tB1\xea\xde\x1f\x05owner\xf2\xde\x1f\x0cyaml:\"owner\"\xd2\xb4-\x14\x63osmos.AddressString\x12<\n\x08host_uri\x18\x02 \x01(\tB*\xe2\xde\x1f\x07HostURI\xea\xde\x1f\x08host_uri\xf2\xde\x1f\x0fyaml:\"host_uri\"\x12\x96\x01\n\nattributes\x18\x03 \x03(\x0b\x32#.akash.base.attributes.v1.AttributeB]\xc8\xde\x1f\x00\xea\xde\x1f\nattributes\xf2\xde\x1f\x11yaml:\"attributes\"\xaa\xdf\x1f\x32pkg.akt.dev/go/node/types/attributes/v1.Attributes\x12G\n\x04info\x18\x04 \x01(\x0b\x32\x1c.akash.provider.v1beta4.InfoB\x1b\xc8\xde\x1f\x00\xea\xde\x1f\x04info\xf2\xde\x1f\x0byaml:\"info\":\x08\x98\xa0\x1f\x00\xe8\xa0\x1f\x00\x42&Z$pkg.akt.dev/go/node/provider/v1beta4b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'akash.provider.v1beta4.provider_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z$pkg.akt.dev/go/node/provider/v1beta4'
  _globals['_INFO'].fields_by_name['email']._options = None
  _globals['_INFO'].fields_by_name['email']._serialized_options = b'\342\336\037\005EMail\352\336\037\005email\362\336\037\014yaml:\"email\"'
  _globals['_INFO'].fields_by_name['website']._options = None
  _globals['_INFO'].fields_by_name['website']._serialized_options = b'\352\336\037\007website\362\336\037\016yaml:\"website\"'
  _globals['_PROVIDER'].fields_by_name['owner']._options = None
  _globals['_PROVIDER'].fields_by_name['owner']._serialized_options = b'\352\336\037\005owner\362\336\037\014yaml:\"owner\"\322\264-\024cosmos.AddressString'
  _globals['_PROVIDER'].fields_by_name['host_uri']._options = None
  _globals['_PROVIDER'].fields_by_name['host_uri']._serialized_options = b'\342\336\037\007HostURI\352\336\037\010host_uri\362\336\037\017yaml:\"host_uri\"'
  _globals['_PROVIDER'].fields_by_name['attributes']._options = None
  _globals['_PROVIDER'].fields_by_name['attributes']._serialized_options = b'\310\336\037\000\352\336\037\nattributes\362\336\037\021yaml:\"attributes\"\252\337\0372pkg.akt.dev/go/node/types/attributes/v1.Attributes'
  _globals['_PROVIDER'].fields_by_name['info']._options = None
  _globals['_PROVIDER'].fields_by_name['info']._serialized_options = b'\310\336\037\000\352\336\037\004info\362\336\037\013yaml:\"info\"'
  _globals['_PROVIDER']._options = None
  _globals['_PROVIDER']._serialized_options = b'\230\240\037\000\350\240\037\000'
  _globals['_INFO']._serialized_start=156
  _globals['_INFO']._serialized_end=261
  _globals['_PROVIDER']._serialized_start=264
  _globals['_PROVIDER']._serialized_end=638
# @@protoc_insertion_point(module_scope)
