# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: akash/provider/v1beta4/service.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from akash.proto.cosmos.msg.v1 import msg_pb2 as cosmos_dot_msg_dot_v1_dot_msg__pb2
from akash.proto.akash.provider.v1beta4 import msg_pb2 as akash_dot_provider_dot_v1beta4_dot_msg__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n$akash/provider/v1beta4/service.proto\x12\x16\x61kash.provider.v1beta4\x1a\x17\x63osmos/msg/v1/msg.proto\x1a akash/provider/v1beta4/msg.proto2\xdc\x02\n\x03Msg\x12n\n\x0e\x43reateProvider\x12).akash.provider.v1beta4.MsgCreateProvider\x1a\x31.akash.provider.v1beta4.MsgCreateProviderResponse\x12n\n\x0eUpdateProvider\x12).akash.provider.v1beta4.MsgUpdateProvider\x1a\x31.akash.provider.v1beta4.MsgUpdateProviderResponse\x12n\n\x0e\x44\x65leteProvider\x12).akash.provider.v1beta4.MsgDeleteProvider\x1a\x31.akash.provider.v1beta4.MsgDeleteProviderResponse\x1a\x05\x80\xe7\xb0*\x01\x42&Z$pkg.akt.dev/go/node/provider/v1beta4b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'akash.provider.v1beta4.service_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z$pkg.akt.dev/go/node/provider/v1beta4'
  _globals['_MSG']._options = None
  _globals['_MSG']._serialized_options = b'\200\347\260*\001'
  _globals['_MSG']._serialized_start=124
  _globals['_MSG']._serialized_end=472
# @@protoc_insertion_point(module_scope)
