# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: akash/escrow/types/v1/account.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from akash.proto.gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2
from akash.proto.cosmos_proto import cosmos_pb2 as cosmos__proto_dot_cosmos__pb2
from akash.proto.cosmos.base.v1beta1 import coin_pb2 as cosmos_dot_base_dot_v1beta1_dot_coin__pb2
from akash.proto.akash.escrow.id.v1 import id_pb2 as akash_dot_escrow_dot_id_dot_v1_dot_id__pb2
from akash.proto.akash.escrow.types.v1 import balance_pb2 as akash_dot_escrow_dot_types_dot_v1_dot_balance__pb2
from akash.proto.akash.escrow.types.v1 import deposit_pb2 as akash_dot_escrow_dot_types_dot_v1_dot_deposit__pb2
from akash.proto.akash.escrow.types.v1 import state_pb2 as akash_dot_escrow_dot_types_dot_v1_dot_state__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#akash/escrow/types/v1/account.proto\x12\x15\x61kash.escrow.types.v1\x1a\x14gogoproto/gogo.proto\x1a\x19\x63osmos_proto/cosmos.proto\x1a\x1e\x63osmos/base/v1beta1/coin.proto\x1a\x1b\x61kash/escrow/id/v1/id.proto\x1a#akash/escrow/types/v1/balance.proto\x1a#akash/escrow/types/v1/deposit.proto\x1a!akash/escrow/types/v1/state.proto\"\x91\x04\n\x0c\x41\x63\x63ountState\x12@\n\x05owner\x18\x01 \x01(\tB1\xea\xde\x1f\x05owner\xf2\xde\x1f\x0cyaml:\"owner\"\xd2\xb4-\x14\x63osmos.AddressString\x12\x46\n\x05state\x18\x02 \x01(\x0e\x32\x1c.akash.escrow.types.v1.StateB\x19\xea\xde\x1f\x05state\xf2\xde\x1f\x0cyaml:\"state\"\x12\x8b\x01\n\x0btransferred\x18\x03 \x03(\x0b\x32\x1c.cosmos.base.v1beta1.DecCoinBX\xc8\xde\x1f\x00\xea\xde\x1f\x0btransferred\xf2\xde\x1f\x12yaml:\"transferred\"\xaa\xdf\x1f+github.com/cosmos/cosmos-sdk/types.DecCoins\x12\x42\n\nsettled_at\x18\x04 \x01(\x03\x42.\xe2\xde\x1f\tSettledAt\xea\xde\x1f\tsettledAt\xf2\xde\x1f\x10yaml:\"settledAt\"\x12L\n\x05\x66unds\x18\x05 \x03(\x0b\x32\x1e.akash.escrow.types.v1.BalanceB\x1d\xc8\xde\x1f\x00\xea\xde\x1f\x05\x66unds\xf2\xde\x1f\x0cyaml:\"funds\"\x12W\n\x08\x64\x65posits\x18\x06 \x03(\x0b\x32 .akash.escrow.types.v1.DepositorB#\xc8\xde\x1f\x00\xea\xde\x1f\x08\x64\x65posits\xf2\xde\x1f\x0fyaml:\"deposits\"\"\xa4\x01\n\x07\x41\x63\x63ount\x12\x46\n\x02id\x18\x01 \x01(\x0b\x32\x1b.akash.escrow.id.v1.AccountB\x1d\xc8\xde\x1f\x00\xe2\xde\x1f\x02ID\xea\xde\x1f\x02id\xf2\xde\x1f\tyaml:\"id\"\x12Q\n\x05state\x18\x02 \x01(\x0b\x32#.akash.escrow.types.v1.AccountStateB\x1d\xc8\xde\x1f\x00\xea\xde\x1f\x05state\xf2\xde\x1f\x0cyaml:\"state\"B%Z#pkg.akt.dev/go/node/escrow/types/v1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'akash.escrow.types.v1.account_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z#pkg.akt.dev/go/node/escrow/types/v1'
  _globals['_ACCOUNTSTATE'].fields_by_name['owner']._options = None
  _globals['_ACCOUNTSTATE'].fields_by_name['owner']._serialized_options = b'\352\336\037\005owner\362\336\037\014yaml:\"owner\"\322\264-\024cosmos.AddressString'
  _globals['_ACCOUNTSTATE'].fields_by_name['state']._options = None
  _globals['_ACCOUNTSTATE'].fields_by_name['state']._serialized_options = b'\352\336\037\005state\362\336\037\014yaml:\"state\"'
  _globals['_ACCOUNTSTATE'].fields_by_name['transferred']._options = None
  _globals['_ACCOUNTSTATE'].fields_by_name['transferred']._serialized_options = b'\310\336\037\000\352\336\037\013transferred\362\336\037\022yaml:\"transferred\"\252\337\037+github.com/cosmos/cosmos-sdk/types.DecCoins'
  _globals['_ACCOUNTSTATE'].fields_by_name['settled_at']._options = None
  _globals['_ACCOUNTSTATE'].fields_by_name['settled_at']._serialized_options = b'\342\336\037\tSettledAt\352\336\037\tsettledAt\362\336\037\020yaml:\"settledAt\"'
  _globals['_ACCOUNTSTATE'].fields_by_name['funds']._options = None
  _globals['_ACCOUNTSTATE'].fields_by_name['funds']._serialized_options = b'\310\336\037\000\352\336\037\005funds\362\336\037\014yaml:\"funds\"'
  _globals['_ACCOUNTSTATE'].fields_by_name['deposits']._options = None
  _globals['_ACCOUNTSTATE'].fields_by_name['deposits']._serialized_options = b'\310\336\037\000\352\336\037\010deposits\362\336\037\017yaml:\"deposits\"'
  _globals['_ACCOUNT'].fields_by_name['id']._options = None
  _globals['_ACCOUNT'].fields_by_name['id']._serialized_options = b'\310\336\037\000\342\336\037\002ID\352\336\037\002id\362\336\037\tyaml:\"id\"'
  _globals['_ACCOUNT'].fields_by_name['state']._options = None
  _globals['_ACCOUNT'].fields_by_name['state']._serialized_options = b'\310\336\037\000\352\336\037\005state\362\336\037\014yaml:\"state\"'
  _globals['_ACCOUNTSTATE']._serialized_start=282
  _globals['_ACCOUNTSTATE']._serialized_end=811
  _globals['_ACCOUNT']._serialized_start=814
  _globals['_ACCOUNT']._serialized_end=978
# @@protoc_insertion_point(module_scope)
