# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: akash/escrow/types/v1/deposit.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from akash.proto.cosmos.base.v1beta1 import coin_pb2 as cosmos_dot_base_dot_v1beta1_dot_coin__pb2
from akash.proto.cosmos_proto import cosmos_pb2 as cosmos__proto_dot_cosmos__pb2
from akash.proto.gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2
from akash.proto.akash.base.deposit.v1 import deposit_pb2 as akash_dot_base_dot_deposit_dot_v1_dot_deposit__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#akash/escrow/types/v1/deposit.proto\x12\x15\x61kash.escrow.types.v1\x1a\x1e\x63osmos/base/v1beta1/coin.proto\x1a\x19\x63osmos_proto/cosmos.proto\x1a\x14gogoproto/gogo.proto\x1a#akash/base/deposit/v1/deposit.proto\"\x98\x02\n\tDepositor\x12@\n\x05owner\x18\x01 \x01(\tB1\xea\xde\x1f\x05owner\xf2\xde\x1f\x0cyaml:\"owner\"\xd2\xb4-\x14\x63osmos.AddressString\x12+\n\x06height\x18\x02 \x01(\x03\x42\x1b\xea\xde\x1f\x06height\xf2\xde\x1f\ryaml:\"height\"\x12J\n\x06source\x18\x03 \x01(\x0e\x32\x1d.akash.base.deposit.v1.SourceB\x1b\xea\xde\x1f\x06source\xf2\xde\x1f\ryaml:\"source\"\x12P\n\x07\x62\x61lance\x18\x04 \x01(\x0b\x32\x1c.cosmos.base.v1beta1.DecCoinB!\xc8\xde\x1f\x00\xea\xde\x1f\x07\x62\x61lance\xf2\xde\x1f\x0eyaml:\"balance\"B%Z#pkg.akt.dev/go/node/escrow/types/v1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'akash.escrow.types.v1.deposit_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z#pkg.akt.dev/go/node/escrow/types/v1'
  _globals['_DEPOSITOR'].fields_by_name['owner']._options = None
  _globals['_DEPOSITOR'].fields_by_name['owner']._serialized_options = b'\352\336\037\005owner\362\336\037\014yaml:\"owner\"\322\264-\024cosmos.AddressString'
  _globals['_DEPOSITOR'].fields_by_name['height']._options = None
  _globals['_DEPOSITOR'].fields_by_name['height']._serialized_options = b'\352\336\037\006height\362\336\037\ryaml:\"height\"'
  _globals['_DEPOSITOR'].fields_by_name['source']._options = None
  _globals['_DEPOSITOR'].fields_by_name['source']._serialized_options = b'\352\336\037\006source\362\336\037\ryaml:\"source\"'
  _globals['_DEPOSITOR'].fields_by_name['balance']._options = None
  _globals['_DEPOSITOR'].fields_by_name['balance']._serialized_options = b'\310\336\037\000\352\336\037\007balance\362\336\037\016yaml:\"balance\"'
  _globals['_DEPOSITOR']._serialized_start=181
  _globals['_DEPOSITOR']._serialized_end=461
# @@protoc_insertion_point(module_scope)
