# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: akash/escrow/types/v1/payment.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from akash.proto.cosmos.base.v1beta1 import coin_pb2 as cosmos_dot_base_dot_v1beta1_dot_coin__pb2
from akash.proto.cosmos_proto import cosmos_pb2 as cosmos__proto_dot_cosmos__pb2
from akash.proto.gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2
from akash.proto.akash.escrow.id.v1 import id_pb2 as akash_dot_escrow_dot_id_dot_v1_dot_id__pb2
from akash.proto.akash.escrow.types.v1 import state_pb2 as akash_dot_escrow_dot_types_dot_v1_dot_state__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#akash/escrow/types/v1/payment.proto\x12\x15\x61kash.escrow.types.v1\x1a\x1e\x63osmos/base/v1beta1/coin.proto\x1a\x19\x63osmos_proto/cosmos.proto\x1a\x14gogoproto/gogo.proto\x1a\x1b\x61kash/escrow/id/v1/id.proto\x1a!akash/escrow/types/v1/state.proto\"\xe0\x03\n\x0cPaymentState\x12@\n\x05owner\x18\x01 \x01(\tB1\xea\xde\x1f\x05owner\xf2\xde\x1f\x0cyaml:\"owner\"\xd2\xb4-\x14\x63osmos.AddressString\x12\x46\n\x05state\x18\x02 \x01(\x0e\x32\x1c.akash.escrow.types.v1.StateB\x19\xea\xde\x1f\x05state\xf2\xde\x1f\x0cyaml:\"state\"\x12G\n\x04rate\x18\x03 \x01(\x0b\x32\x1c.cosmos.base.v1beta1.DecCoinB\x1b\xc8\xde\x1f\x00\xea\xde\x1f\x04rate\xf2\xde\x1f\x0byaml:\"rate\"\x12P\n\x07\x62\x61lance\x18\x04 \x01(\x0b\x32\x1c.cosmos.base.v1beta1.DecCoinB!\xc8\xde\x1f\x00\xea\xde\x1f\x07\x62\x61lance\xf2\xde\x1f\x0eyaml:\"balance\"\x12V\n\tunsettled\x18\x05 \x01(\x0b\x32\x1c.cosmos.base.v1beta1.DecCoinB%\xc8\xde\x1f\x00\xea\xde\x1f\tunsettled\xf2\xde\x1f\x10yaml:\"unsettled\"\x12S\n\twithdrawn\x18\x06 \x01(\x0b\x32\x19.cosmos.base.v1beta1.CoinB%\xc8\xde\x1f\x00\xea\xde\x1f\twithdrawn\xf2\xde\x1f\x10yaml:\"withdrawn\"\"\xa4\x01\n\x07Payment\x12\x46\n\x02id\x18\x01 \x01(\x0b\x32\x1b.akash.escrow.id.v1.PaymentB\x1d\xc8\xde\x1f\x00\xe2\xde\x1f\x02ID\xea\xde\x1f\x02id\xf2\xde\x1f\tyaml:\"id\"\x12Q\n\x05state\x18\x02 \x01(\x0b\x32#.akash.escrow.types.v1.PaymentStateB\x1d\xc8\xde\x1f\x00\xea\xde\x1f\x05state\xf2\xde\x1f\x0cyaml:\"state\"B%Z#pkg.akt.dev/go/node/escrow/types/v1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'akash.escrow.types.v1.payment_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z#pkg.akt.dev/go/node/escrow/types/v1'
  _globals['_PAYMENTSTATE'].fields_by_name['owner']._options = None
  _globals['_PAYMENTSTATE'].fields_by_name['owner']._serialized_options = b'\352\336\037\005owner\362\336\037\014yaml:\"owner\"\322\264-\024cosmos.AddressString'
  _globals['_PAYMENTSTATE'].fields_by_name['state']._options = None
  _globals['_PAYMENTSTATE'].fields_by_name['state']._serialized_options = b'\352\336\037\005state\362\336\037\014yaml:\"state\"'
  _globals['_PAYMENTSTATE'].fields_by_name['rate']._options = None
  _globals['_PAYMENTSTATE'].fields_by_name['rate']._serialized_options = b'\310\336\037\000\352\336\037\004rate\362\336\037\013yaml:\"rate\"'
  _globals['_PAYMENTSTATE'].fields_by_name['balance']._options = None
  _globals['_PAYMENTSTATE'].fields_by_name['balance']._serialized_options = b'\310\336\037\000\352\336\037\007balance\362\336\037\016yaml:\"balance\"'
  _globals['_PAYMENTSTATE'].fields_by_name['unsettled']._options = None
  _globals['_PAYMENTSTATE'].fields_by_name['unsettled']._serialized_options = b'\310\336\037\000\352\336\037\tunsettled\362\336\037\020yaml:\"unsettled\"'
  _globals['_PAYMENTSTATE'].fields_by_name['withdrawn']._options = None
  _globals['_PAYMENTSTATE'].fields_by_name['withdrawn']._serialized_options = b'\310\336\037\000\352\336\037\twithdrawn\362\336\037\020yaml:\"withdrawn\"'
  _globals['_PAYMENT'].fields_by_name['id']._options = None
  _globals['_PAYMENT'].fields_by_name['id']._serialized_options = b'\310\336\037\000\342\336\037\002ID\352\336\037\002id\362\336\037\tyaml:\"id\"'
  _globals['_PAYMENT'].fields_by_name['state']._options = None
  _globals['_PAYMENT'].fields_by_name['state']._serialized_options = b'\310\336\037\000\352\336\037\005state\362\336\037\014yaml:\"state\"'
  _globals['_PAYMENTSTATE']._serialized_start=208
  _globals['_PAYMENTSTATE']._serialized_end=688
  _globals['_PAYMENT']._serialized_start=691
  _globals['_PAYMENT']._serialized_end=855
# @@protoc_insertion_point(module_scope)
