# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: akash/escrow/types/v1/state.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from akash.proto.gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!akash/escrow/types/v1/state.proto\x12\x15\x61kash.escrow.types.v1\x1a\x14gogoproto/gogo.proto*\x85\x01\n\x05State\x12\x1d\n\x07invalid\x10\x00\x1a\x10\x8a\x9d \x0cStateInvalid\x12\x17\n\x04open\x10\x01\x1a\r\x8a\x9d \tStateOpen\x12\x1b\n\x06\x63losed\x10\x02\x1a\x0f\x8a\x9d \x0bStateClosed\x12!\n\toverdrawn\x10\x03\x1a\x12\x8a\x9d \x0eStateOverdrawn\x1a\x04\x88\xa3\x1e\x00\x42%Z#pkg.akt.dev/go/node/escrow/types/v1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'akash.escrow.types.v1.state_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z#pkg.akt.dev/go/node/escrow/types/v1'
  _globals['_STATE']._options = None
  _globals['_STATE']._serialized_options = b'\210\243\036\000'
  _globals['_STATE'].values_by_name["invalid"]._options = None
  _globals['_STATE'].values_by_name["invalid"]._serialized_options = b'\212\235 \014StateInvalid'
  _globals['_STATE'].values_by_name["open"]._options = None
  _globals['_STATE'].values_by_name["open"]._serialized_options = b'\212\235 \tStateOpen'
  _globals['_STATE'].values_by_name["closed"]._options = None
  _globals['_STATE'].values_by_name["closed"]._serialized_options = b'\212\235 \013StateClosed'
  _globals['_STATE'].values_by_name["overdrawn"]._options = None
  _globals['_STATE'].values_by_name["overdrawn"]._serialized_options = b'\212\235 \016StateOverdrawn'
  _globals['_STATE']._serialized_start=83
  _globals['_STATE']._serialized_end=216
# @@protoc_insertion_point(module_scope)
