# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: akash/base/attributes/v1/attribute.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from akash.proto.gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n(akash/base/attributes/v1/attribute.proto\x12\x18\x61kash.base.attributes.v1\x1a\x14gogoproto/gogo.proto\"S\n\tAttribute\x12\x1b\n\x03key\x18\x01 \x01(\tB\x0e\xf2\xde\x1f\nyaml:\"key\"\x12\x1f\n\x05value\x18\x02 \x01(\tB\x10\xf2\xde\x1f\x0cyaml:\"value\":\x08\x88\xa0\x1f\x00\xe8\xa0\x1f\x00\"p\n\x08SignedBy\x12*\n\x06\x61ll_of\x18\x01 \x03(\tB\x1a\xea\xde\x1f\x06\x61ll_of\xf2\xde\x1f\x0cyaml:\"allOf\"\x12*\n\x06\x61ny_of\x18\x02 \x03(\tB\x1a\xea\xde\x1f\x06\x61ny_of\xf2\xde\x1f\x0cyaml:\"anyOf\":\x0c\x88\xa0\x1f\x00\xe8\xa0\x1f\x01\x80\xdc \x00\"\xf3\x01\n\x15PlacementRequirements\x12\\\n\tsigned_by\x18\x01 \x01(\x0b\x32\".akash.base.attributes.v1.SignedByB%\xc8\xde\x1f\x00\xea\xde\x1f\tsigned_by\xf2\xde\x1f\x10yaml:\"signed_by\"\x12n\n\nattributes\x18\x02 \x03(\x0b\x32#.akash.base.attributes.v1.AttributeB5\xc8\xde\x1f\x00\xea\xde\x1f\nattributes\xf2\xde\x1f\x11yaml:\"attributes\"\xaa\xdf\x1f\nAttributes:\x0c\x88\xa0\x1f\x00\xe8\xa0\x1f\x01\x80\xdc \x00\x42\x31Z\'pkg.akt.dev/go/node/types/attributes/v1\xd8\xe1\x1e\x00\x80\xe2\x1e\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'akash.base.attributes.v1.attribute_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\'pkg.akt.dev/go/node/types/attributes/v1\330\341\036\000\200\342\036\000'
  _globals['_ATTRIBUTE'].fields_by_name['key']._options = None
  _globals['_ATTRIBUTE'].fields_by_name['key']._serialized_options = b'\362\336\037\nyaml:\"key\"'
  _globals['_ATTRIBUTE'].fields_by_name['value']._options = None
  _globals['_ATTRIBUTE'].fields_by_name['value']._serialized_options = b'\362\336\037\014yaml:\"value\"'
  _globals['_ATTRIBUTE']._options = None
  _globals['_ATTRIBUTE']._serialized_options = b'\210\240\037\000\350\240\037\000'
  _globals['_SIGNEDBY'].fields_by_name['all_of']._options = None
  _globals['_SIGNEDBY'].fields_by_name['all_of']._serialized_options = b'\352\336\037\006all_of\362\336\037\014yaml:\"allOf\"'
  _globals['_SIGNEDBY'].fields_by_name['any_of']._options = None
  _globals['_SIGNEDBY'].fields_by_name['any_of']._serialized_options = b'\352\336\037\006any_of\362\336\037\014yaml:\"anyOf\"'
  _globals['_SIGNEDBY']._options = None
  _globals['_SIGNEDBY']._serialized_options = b'\210\240\037\000\350\240\037\001\200\334 \000'
  _globals['_PLACEMENTREQUIREMENTS'].fields_by_name['signed_by']._options = None
  _globals['_PLACEMENTREQUIREMENTS'].fields_by_name['signed_by']._serialized_options = b'\310\336\037\000\352\336\037\tsigned_by\362\336\037\020yaml:\"signed_by\"'
  _globals['_PLACEMENTREQUIREMENTS'].fields_by_name['attributes']._options = None
  _globals['_PLACEMENTREQUIREMENTS'].fields_by_name['attributes']._serialized_options = b'\310\336\037\000\352\336\037\nattributes\362\336\037\021yaml:\"attributes\"\252\337\037\nAttributes'
  _globals['_PLACEMENTREQUIREMENTS']._options = None
  _globals['_PLACEMENTREQUIREMENTS']._serialized_options = b'\210\240\037\000\350\240\037\001\200\334 \000'
  _globals['_ATTRIBUTE']._serialized_start=92
  _globals['_ATTRIBUTE']._serialized_end=175
  _globals['_SIGNEDBY']._serialized_start=177
  _globals['_SIGNEDBY']._serialized_end=289
  _globals['_PLACEMENTREQUIREMENTS']._serialized_start=292
  _globals['_PLACEMENTREQUIREMENTS']._serialized_end=535
# @@protoc_insertion_point(module_scope)
