# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: akash/escrow/id/v1/id.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from akash.proto.gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1b\x61kash/escrow/id/v1/id.proto\x12\x12\x61kash.escrow.id.v1\x1a\x14gogoproto/gogo.proto\"\x7f\n\x07\x41\x63\x63ount\x12\x43\n\x05scope\x18\x01 \x01(\x0e\x32\x19.akash.escrow.id.v1.ScopeB\x19\xea\xde\x1f\x05scope\xf2\xde\x1f\x0cyaml:\"scope\"\x12)\n\x03xid\x18\x02 \x01(\tB\x1c\xe2\xde\x1f\x03XID\xea\xde\x1f\x03xid\xf2\xde\x1f\nyaml:\"xid\":\x04\x98\xa0\x1f\x01\"\x86\x01\n\x07Payment\x12J\n\x03\x61id\x18\x01 \x01(\x0b\x32\x1b.akash.escrow.id.v1.AccountB \xc8\xde\x1f\x00\xe2\xde\x1f\x03\x41ID\xea\xde\x1f\x03\x61id\xf2\xde\x1f\nyaml:\"aid\"\x12)\n\x03xid\x18\x02 \x01(\tB\x1c\xe2\xde\x1f\x03XID\xea\xde\x1f\x03xid\xf2\xde\x1f\nyaml:\"xid\":\x04\x98\xa0\x1f\x01*h\n\x05Scope\x12\x1d\n\x07invalid\x10\x00\x1a\x10\x8a\x9d \x0cScopeInvalid\x12#\n\ndeployment\x10\x01\x1a\x13\x8a\x9d \x0fScopeDeployment\x12\x15\n\x03\x62id\x10\x02\x1a\x0c\x8a\x9d \x08ScopeBid\x1a\x04\x88\xa3\x1e\x00\x42\"Z pkg.akt.dev/go/node/escrow/id/v1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'akash.escrow.id.v1.id_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z pkg.akt.dev/go/node/escrow/id/v1'
  _globals['_SCOPE']._options = None
  _globals['_SCOPE']._serialized_options = b'\210\243\036\000'
  _globals['_SCOPE'].values_by_name["invalid"]._options = None
  _globals['_SCOPE'].values_by_name["invalid"]._serialized_options = b'\212\235 \014ScopeInvalid'
  _globals['_SCOPE'].values_by_name["deployment"]._options = None
  _globals['_SCOPE'].values_by_name["deployment"]._serialized_options = b'\212\235 \017ScopeDeployment'
  _globals['_SCOPE'].values_by_name["bid"]._options = None
  _globals['_SCOPE'].values_by_name["bid"]._serialized_options = b'\212\235 \010ScopeBid'
  _globals['_ACCOUNT'].fields_by_name['scope']._options = None
  _globals['_ACCOUNT'].fields_by_name['scope']._serialized_options = b'\352\336\037\005scope\362\336\037\014yaml:\"scope\"'
  _globals['_ACCOUNT'].fields_by_name['xid']._options = None
  _globals['_ACCOUNT'].fields_by_name['xid']._serialized_options = b'\342\336\037\003XID\352\336\037\003xid\362\336\037\nyaml:\"xid\"'
  _globals['_ACCOUNT']._options = None
  _globals['_ACCOUNT']._serialized_options = b'\230\240\037\001'
  _globals['_PAYMENT'].fields_by_name['aid']._options = None
  _globals['_PAYMENT'].fields_by_name['aid']._serialized_options = b'\310\336\037\000\342\336\037\003AID\352\336\037\003aid\362\336\037\nyaml:\"aid\"'
  _globals['_PAYMENT'].fields_by_name['xid']._options = None
  _globals['_PAYMENT'].fields_by_name['xid']._serialized_options = b'\342\336\037\003XID\352\336\037\003xid\362\336\037\nyaml:\"xid\"'
  _globals['_PAYMENT']._options = None
  _globals['_PAYMENT']._serialized_options = b'\230\240\037\001'
  _globals['_SCOPE']._serialized_start=339
  _globals['_SCOPE']._serialized_end=443
  _globals['_ACCOUNT']._serialized_start=73
  _globals['_ACCOUNT']._serialized_end=200
  _globals['_PAYMENT']._serialized_start=203
  _globals['_PAYMENT']._serialized_end=337
# @@protoc_insertion_point(module_scope)
