# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: akash/base/resources/v1beta4/cpu.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from akash.proto.gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2
from akash.proto.akash.base.attributes.v1 import attribute_pb2 as akash_dot_base_dot_attributes_dot_v1_dot_attribute__pb2
from akash.proto.akash.base.resources.v1beta4 import resourcevalue_pb2 as akash_dot_base_dot_resources_dot_v1beta4_dot_resourcevalue__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&akash/base/resources/v1beta4/cpu.proto\x12\x1c\x61kash.base.resources.v1beta4\x1a\x14gogoproto/gogo.proto\x1a(akash/base/attributes/v1/attribute.proto\x1a\x30\x61kash/base/resources/v1beta4/resourcevalue.proto\"\xfa\x01\n\x03\x43PU\x12@\n\x05units\x18\x01 \x01(\x0b\x32+.akash.base.resources.v1beta4.ResourceValueB\x04\xc8\xde\x1f\x00\x12\xaa\x01\n\nattributes\x18\x02 \x03(\x0b\x32#.akash.base.attributes.v1.AttributeBq\xc8\xde\x1f\x00\xea\xde\x1f\x14\x61ttributes,omitempty\xf2\xde\x1f\x1byaml:\"attributes,omitempty\"\xaa\xdf\x1f\x32pkg.akt.dev/go/node/types/attributes/v1.Attributes:\x04\xe8\xa0\x1f\x01\x42-Z+pkg.akt.dev/go/node/types/resources/v1beta4b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'akash.base.resources.v1beta4.cpu_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z+pkg.akt.dev/go/node/types/resources/v1beta4'
  _globals['_CPU'].fields_by_name['units']._options = None
  _globals['_CPU'].fields_by_name['units']._serialized_options = b'\310\336\037\000'
  _globals['_CPU'].fields_by_name['attributes']._options = None
  _globals['_CPU'].fields_by_name['attributes']._serialized_options = b'\310\336\037\000\352\336\037\024attributes,omitempty\362\336\037\033yaml:\"attributes,omitempty\"\252\337\0372pkg.akt.dev/go/node/types/attributes/v1.Attributes'
  _globals['_CPU']._options = None
  _globals['_CPU']._serialized_options = b'\350\240\037\001'
  _globals['_CPU']._serialized_start=187
  _globals['_CPU']._serialized_end=437
# @@protoc_insertion_point(module_scope)
