# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: akash/base/resources/v1beta4/resources.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from akash.proto.gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2
from akash.proto.akash.base.resources.v1beta4 import cpu_pb2 as akash_dot_base_dot_resources_dot_v1beta4_dot_cpu__pb2
from akash.proto.akash.base.resources.v1beta4 import gpu_pb2 as akash_dot_base_dot_resources_dot_v1beta4_dot_gpu__pb2
from akash.proto.akash.base.resources.v1beta4 import memory_pb2 as akash_dot_base_dot_resources_dot_v1beta4_dot_memory__pb2
from akash.proto.akash.base.resources.v1beta4 import storage_pb2 as akash_dot_base_dot_resources_dot_v1beta4_dot_storage__pb2
from akash.proto.akash.base.resources.v1beta4 import endpoint_pb2 as akash_dot_base_dot_resources_dot_v1beta4_dot_endpoint__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n,akash/base/resources/v1beta4/resources.proto\x12\x1c\x61kash.base.resources.v1beta4\x1a\x14gogoproto/gogo.proto\x1a&akash/base/resources/v1beta4/cpu.proto\x1a&akash/base/resources/v1beta4/gpu.proto\x1a)akash/base/resources/v1beta4/memory.proto\x1a*akash/base/resources/v1beta4/storage.proto\x1a+akash/base/resources/v1beta4/endpoint.proto\"\xd8\x04\n\tResources\x12%\n\x02id\x18\x01 \x01(\rB\x19\xe2\xde\x1f\x02ID\xea\xde\x1f\x02id\xf2\xde\x1f\tyaml:\"id\"\x12\x64\n\x03\x63pu\x18\x02 \x01(\x0b\x32!.akash.base.resources.v1beta4.CPUB4\xc8\xde\x1f\x01\xe2\xde\x1f\x03\x43PU\xea\xde\x1f\rcpu,omitempty\xf2\xde\x1f\x14yaml:\"cpu,omitempty\"\x12i\n\x06memory\x18\x03 \x01(\x0b\x32$.akash.base.resources.v1beta4.MemoryB3\xc8\xde\x1f\x01\xea\xde\x1f\x10memory,omitempty\xf2\xde\x1f\x17yaml:\"memory,omitempty\"\x12x\n\x07storage\x18\x04 \x03(\x0b\x32%.akash.base.resources.v1beta4.StorageB@\xc8\xde\x1f\x00\xea\xde\x1f\x11storage,omitempty\xf2\xde\x1f\x18yaml:\"storage,omitempty\"\xaa\xdf\x1f\x07Volumes\x12\x64\n\x03gpu\x18\x05 \x01(\x0b\x32!.akash.base.resources.v1beta4.GPUB4\xc8\xde\x1f\x01\xe2\xde\x1f\x03GPU\xea\xde\x1f\rgpu,omitempty\xf2\xde\x1f\x14yaml:\"gpu,omitempty\"\x12m\n\tendpoints\x18\x06 \x03(\x0b\x32&.akash.base.resources.v1beta4.EndpointB2\xc8\xde\x1f\x00\xea\xde\x1f\tendpoints\xf2\xde\x1f\x10yaml:\"endpoints\"\xaa\xdf\x1f\tEndpoints:\x04\xe8\xa0\x1f\x01\x42-Z+pkg.akt.dev/go/node/types/resources/v1beta4b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'akash.base.resources.v1beta4.resources_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z+pkg.akt.dev/go/node/types/resources/v1beta4'
  _globals['_RESOURCES'].fields_by_name['id']._options = None
  _globals['_RESOURCES'].fields_by_name['id']._serialized_options = b'\342\336\037\002ID\352\336\037\002id\362\336\037\tyaml:\"id\"'
  _globals['_RESOURCES'].fields_by_name['cpu']._options = None
  _globals['_RESOURCES'].fields_by_name['cpu']._serialized_options = b'\310\336\037\001\342\336\037\003CPU\352\336\037\rcpu,omitempty\362\336\037\024yaml:\"cpu,omitempty\"'
  _globals['_RESOURCES'].fields_by_name['memory']._options = None
  _globals['_RESOURCES'].fields_by_name['memory']._serialized_options = b'\310\336\037\001\352\336\037\020memory,omitempty\362\336\037\027yaml:\"memory,omitempty\"'
  _globals['_RESOURCES'].fields_by_name['storage']._options = None
  _globals['_RESOURCES'].fields_by_name['storage']._serialized_options = b'\310\336\037\000\352\336\037\021storage,omitempty\362\336\037\030yaml:\"storage,omitempty\"\252\337\037\007Volumes'
  _globals['_RESOURCES'].fields_by_name['gpu']._options = None
  _globals['_RESOURCES'].fields_by_name['gpu']._serialized_options = b'\310\336\037\001\342\336\037\003GPU\352\336\037\rgpu,omitempty\362\336\037\024yaml:\"gpu,omitempty\"'
  _globals['_RESOURCES'].fields_by_name['endpoints']._options = None
  _globals['_RESOURCES'].fields_by_name['endpoints']._serialized_options = b'\310\336\037\000\352\336\037\tendpoints\362\336\037\020yaml:\"endpoints\"\252\337\037\tEndpoints'
  _globals['_RESOURCES']._options = None
  _globals['_RESOURCES']._serialized_options = b'\350\240\037\001'
  _globals['_RESOURCES']._serialized_start=313
  _globals['_RESOURCES']._serialized_end=913
# @@protoc_insertion_point(module_scope)
