# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: akash/base/resources/v1beta4/resourcevalue.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from akash.proto.gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n0akash/base/resources/v1beta4/resourcevalue.proto\x12\x1c\x61kash.base.resources.v1beta4\x1a\x14gogoproto/gogo.proto\"A\n\rResourceValue\x12*\n\x03val\x18\x01 \x01(\x0c\x42\x1d\xc8\xde\x1f\x00\xda\xde\x1f\x15\x63osmossdk.io/math.Int:\x04\xe8\xa0\x1f\x01\x42-Z+pkg.akt.dev/go/node/types/resources/v1beta4b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'akash.base.resources.v1beta4.resourcevalue_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z+pkg.akt.dev/go/node/types/resources/v1beta4'
  _globals['_RESOURCEVALUE'].fields_by_name['val']._options = None
  _globals['_RESOURCEVALUE'].fields_by_name['val']._serialized_options = b'\310\336\037\000\332\336\037\025cosmossdk.io/math.Int'
  _globals['_RESOURCEVALUE']._options = None
  _globals['_RESOURCEVALUE']._serialized_options = b'\350\240\037\001'
  _globals['_RESOURCEVALUE']._serialized_start=104
  _globals['_RESOURCEVALUE']._serialized_end=169
# @@protoc_insertion_point(module_scope)
