# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: akash/deployment/v1/event.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from akash.proto.gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2
from akash.proto.akash.deployment.v1 import deployment_pb2 as akash_dot_deployment_dot_v1_dot_deployment__pb2
from akash.proto.akash.deployment.v1 import group_pb2 as akash_dot_deployment_dot_v1_dot_group__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1f\x61kash/deployment/v1/event.proto\x12\x13\x61kash.deployment.v1\x1a\x14gogoproto/gogo.proto\x1a$akash/deployment/v1/deployment.proto\x1a\x1f\x61kash/deployment/v1/group.proto\"\x93\x01\n\x16\x45ventDeploymentCreated\x12L\n\x02id\x18\x01 \x01(\x0b\x32!.akash.deployment.v1.DeploymentIDB\x1d\xc8\xde\x1f\x00\xe2\xde\x1f\x02ID\xea\xde\x1f\x02id\xf2\xde\x1f\tyaml:\"id\"\x12%\n\x04hash\x18\x02 \x01(\x0c\x42\x17\xea\xde\x1f\x04hash\xf2\xde\x1f\x0byaml:\"hash\":\x04\xe8\xa0\x1f\x01\"\x93\x01\n\x16\x45ventDeploymentUpdated\x12L\n\x02id\x18\x01 \x01(\x0b\x32!.akash.deployment.v1.DeploymentIDB\x1d\xc8\xde\x1f\x00\xe2\xde\x1f\x02ID\xea\xde\x1f\x02id\xf2\xde\x1f\tyaml:\"id\"\x12%\n\x04hash\x18\x02 \x01(\x0c\x42\x17\xea\xde\x1f\x04hash\xf2\xde\x1f\x0byaml:\"hash\":\x04\xe8\xa0\x1f\x01\"k\n\x15\x45ventDeploymentClosed\x12L\n\x02id\x18\x01 \x01(\x0b\x32!.akash.deployment.v1.DeploymentIDB\x1d\xc8\xde\x1f\x00\xe2\xde\x1f\x02ID\xea\xde\x1f\x02id\xf2\xde\x1f\tyaml:\"id\":\x04\xe8\xa0\x1f\x01\"b\n\x11\x45ventGroupStarted\x12G\n\x02id\x18\x01 \x01(\x0b\x32\x1c.akash.deployment.v1.GroupIDB\x1d\xc8\xde\x1f\x00\xe2\xde\x1f\x02ID\xea\xde\x1f\x02id\xf2\xde\x1f\tyaml:\"id\":\x04\xe8\xa0\x1f\x01\"a\n\x10\x45ventGroupPaused\x12G\n\x02id\x18\x01 \x01(\x0b\x32\x1c.akash.deployment.v1.GroupIDB\x1d\xc8\xde\x1f\x00\xe2\xde\x1f\x02ID\xea\xde\x1f\x02id\xf2\xde\x1f\tyaml:\"id\":\x04\xe8\xa0\x1f\x01\"a\n\x10\x45ventGroupClosed\x12G\n\x02id\x18\x01 \x01(\x0b\x32\x1c.akash.deployment.v1.GroupIDB\x1d\xc8\xde\x1f\x00\xe2\xde\x1f\x02ID\xea\xde\x1f\x02id\xf2\xde\x1f\tyaml:\"id\":\x04\xe8\xa0\x1f\x01\x42#Z!pkg.akt.dev/go/node/deployment/v1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'akash.deployment.v1.event_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z!pkg.akt.dev/go/node/deployment/v1'
  _globals['_EVENTDEPLOYMENTCREATED'].fields_by_name['id']._options = None
  _globals['_EVENTDEPLOYMENTCREATED'].fields_by_name['id']._serialized_options = b'\310\336\037\000\342\336\037\002ID\352\336\037\002id\362\336\037\tyaml:\"id\"'
  _globals['_EVENTDEPLOYMENTCREATED'].fields_by_name['hash']._options = None
  _globals['_EVENTDEPLOYMENTCREATED'].fields_by_name['hash']._serialized_options = b'\352\336\037\004hash\362\336\037\013yaml:\"hash\"'
  _globals['_EVENTDEPLOYMENTCREATED']._options = None
  _globals['_EVENTDEPLOYMENTCREATED']._serialized_options = b'\350\240\037\001'
  _globals['_EVENTDEPLOYMENTUPDATED'].fields_by_name['id']._options = None
  _globals['_EVENTDEPLOYMENTUPDATED'].fields_by_name['id']._serialized_options = b'\310\336\037\000\342\336\037\002ID\352\336\037\002id\362\336\037\tyaml:\"id\"'
  _globals['_EVENTDEPLOYMENTUPDATED'].fields_by_name['hash']._options = None
  _globals['_EVENTDEPLOYMENTUPDATED'].fields_by_name['hash']._serialized_options = b'\352\336\037\004hash\362\336\037\013yaml:\"hash\"'
  _globals['_EVENTDEPLOYMENTUPDATED']._options = None
  _globals['_EVENTDEPLOYMENTUPDATED']._serialized_options = b'\350\240\037\001'
  _globals['_EVENTDEPLOYMENTCLOSED'].fields_by_name['id']._options = None
  _globals['_EVENTDEPLOYMENTCLOSED'].fields_by_name['id']._serialized_options = b'\310\336\037\000\342\336\037\002ID\352\336\037\002id\362\336\037\tyaml:\"id\"'
  _globals['_EVENTDEPLOYMENTCLOSED']._options = None
  _globals['_EVENTDEPLOYMENTCLOSED']._serialized_options = b'\350\240\037\001'
  _globals['_EVENTGROUPSTARTED'].fields_by_name['id']._options = None
  _globals['_EVENTGROUPSTARTED'].fields_by_name['id']._serialized_options = b'\310\336\037\000\342\336\037\002ID\352\336\037\002id\362\336\037\tyaml:\"id\"'
  _globals['_EVENTGROUPSTARTED']._options = None
  _globals['_EVENTGROUPSTARTED']._serialized_options = b'\350\240\037\001'
  _globals['_EVENTGROUPPAUSED'].fields_by_name['id']._options = None
  _globals['_EVENTGROUPPAUSED'].fields_by_name['id']._serialized_options = b'\310\336\037\000\342\336\037\002ID\352\336\037\002id\362\336\037\tyaml:\"id\"'
  _globals['_EVENTGROUPPAUSED']._options = None
  _globals['_EVENTGROUPPAUSED']._serialized_options = b'\350\240\037\001'
  _globals['_EVENTGROUPCLOSED'].fields_by_name['id']._options = None
  _globals['_EVENTGROUPCLOSED'].fields_by_name['id']._serialized_options = b'\310\336\037\000\342\336\037\002ID\352\336\037\002id\362\336\037\tyaml:\"id\"'
  _globals['_EVENTGROUPCLOSED']._options = None
  _globals['_EVENTGROUPCLOSED']._serialized_options = b'\350\240\037\001'
  _globals['_EVENTDEPLOYMENTCREATED']._serialized_start=150
  _globals['_EVENTDEPLOYMENTCREATED']._serialized_end=297
  _globals['_EVENTDEPLOYMENTUPDATED']._serialized_start=300
  _globals['_EVENTDEPLOYMENTUPDATED']._serialized_end=447
  _globals['_EVENTDEPLOYMENTCLOSED']._serialized_start=449
  _globals['_EVENTDEPLOYMENTCLOSED']._serialized_end=556
  _globals['_EVENTGROUPSTARTED']._serialized_start=558
  _globals['_EVENTGROUPSTARTED']._serialized_end=656
  _globals['_EVENTGROUPPAUSED']._serialized_start=658
  _globals['_EVENTGROUPPAUSED']._serialized_end=755
  _globals['_EVENTGROUPCLOSED']._serialized_start=757
  _globals['_EVENTGROUPCLOSED']._serialized_end=854
# @@protoc_insertion_point(module_scope)
