# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: akash/base/deposit/v1/deposit.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from akash.proto.gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2
from akash.proto.cosmos.base.v1beta1 import coin_pb2 as cosmos_dot_base_dot_v1beta1_dot_coin__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#akash/base/deposit/v1/deposit.proto\x12\x15\x61kash.base.deposit.v1\x1a\x14gogoproto/gogo.proto\x1a\x1e\x63osmos/base/v1beta1/coin.proto\"\xb5\x01\n\x07\x44\x65posit\x12@\n\x06\x61mount\x18\x01 \x01(\x0b\x32\x19.cosmos.base.v1beta1.CoinB\x15\xc8\xde\x1f\x00\xf2\xde\x1f\ryaml:\"amount\"\x12h\n\x07sources\x18\x05 \x03(\x0e\x32\x1d.akash.base.deposit.v1.SourceB8\xea\xde\x1f\x0f\x64\x65posit_sources\xf2\xde\x1f\x16yaml:\"deposit_sources\"\xaa\xdf\x1f\x07Sources*j\n\x06Source\x12\x1e\n\x07invalid\x10\x00\x1a\x11\x8a\x9d \rSourceInvalid\x12\x1e\n\x07\x62\x61lance\x10\x01\x1a\x11\x8a\x9d \rSourceBalance\x12\x1a\n\x05grant\x10\x02\x1a\x0f\x8a\x9d \x0bSourceGrant\x1a\x04\x88\xa3\x1e\x00\x42&Z$pkg.akt.dev/go/node/types/deposit/v1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'akash.base.deposit.v1.deposit_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z$pkg.akt.dev/go/node/types/deposit/v1'
  _globals['_SOURCE']._options = None
  _globals['_SOURCE']._serialized_options = b'\210\243\036\000'
  _globals['_SOURCE'].values_by_name["invalid"]._options = None
  _globals['_SOURCE'].values_by_name["invalid"]._serialized_options = b'\212\235 \rSourceInvalid'
  _globals['_SOURCE'].values_by_name["balance"]._options = None
  _globals['_SOURCE'].values_by_name["balance"]._serialized_options = b'\212\235 \rSourceBalance'
  _globals['_SOURCE'].values_by_name["grant"]._options = None
  _globals['_SOURCE'].values_by_name["grant"]._serialized_options = b'\212\235 \013SourceGrant'
  _globals['_DEPOSIT'].fields_by_name['amount']._options = None
  _globals['_DEPOSIT'].fields_by_name['amount']._serialized_options = b'\310\336\037\000\362\336\037\ryaml:\"amount\"'
  _globals['_DEPOSIT'].fields_by_name['sources']._options = None
  _globals['_DEPOSIT'].fields_by_name['sources']._serialized_options = b'\352\336\037\017deposit_sources\362\336\037\026yaml:\"deposit_sources\"\252\337\037\007Sources'
  _globals['_SOURCE']._serialized_start=300
  _globals['_SOURCE']._serialized_end=406
  _globals['_DEPOSIT']._serialized_start=117
  _globals['_DEPOSIT']._serialized_end=298
# @@protoc_insertion_point(module_scope)
