# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: akash/escrow/v1/genesis.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from akash.proto.gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2
from akash.proto.akash.escrow.types.v1 import account_pb2 as akash_dot_escrow_dot_types_dot_v1_dot_account__pb2
from akash.proto.akash.escrow.types.v1 import payment_pb2 as akash_dot_escrow_dot_types_dot_v1_dot_payment__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1d\x61kash/escrow/v1/genesis.proto\x12\x0f\x61kash.escrow.v1\x1a\x14gogoproto/gogo.proto\x1a#akash/escrow/types/v1/account.proto\x1a#akash/escrow/types/v1/payment.proto\"\x9e\x02\n\x0cGenesisState\x12\x85\x01\n\x08\x61\x63\x63ounts\x18\x01 \x03(\x0b\x32\x1e.akash.escrow.types.v1.AccountBS\xc8\xde\x1f\x00\xea\xde\x1f\x08\x61\x63\x63ounts\xf2\xde\x1f\x0fyaml:\"accounts\"\xaa\xdf\x1f,pkg.akt.dev/go/node/escrow/types/v1.Accounts\x12\x85\x01\n\x08payments\x18\x02 \x03(\x0b\x32\x1e.akash.escrow.types.v1.PaymentBS\xc8\xde\x1f\x00\xea\xde\x1f\x08payments\xf2\xde\x1f\x0fyaml:\"payments\"\xaa\xdf\x1f,pkg.akt.dev/go/node/escrow/types/v1.PaymentsB\x1fZ\x1dpkg.akt.dev/go/node/escrow/v1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'akash.escrow.v1.genesis_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\035pkg.akt.dev/go/node/escrow/v1'
  _globals['_GENESISSTATE'].fields_by_name['accounts']._options = None
  _globals['_GENESISSTATE'].fields_by_name['accounts']._serialized_options = b'\310\336\037\000\352\336\037\010accounts\362\336\037\017yaml:\"accounts\"\252\337\037,pkg.akt.dev/go/node/escrow/types/v1.Accounts'
  _globals['_GENESISSTATE'].fields_by_name['payments']._options = None
  _globals['_GENESISSTATE'].fields_by_name['payments']._serialized_options = b'\310\336\037\000\352\336\037\010payments\362\336\037\017yaml:\"payments\"\252\337\037,pkg.akt.dev/go/node/escrow/types/v1.Payments'
  _globals['_GENESISSTATE']._serialized_start=147
  _globals['_GENESISSTATE']._serialized_end=433
# @@protoc_insertion_point(module_scope)
