# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: akash/escrow/v1/msg.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from akash.proto.gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2
from akash.proto.cosmos_proto import cosmos_pb2 as cosmos__proto_dot_cosmos__pb2
from akash.proto.cosmos.msg.v1 import msg_pb2 as cosmos_dot_msg_dot_v1_dot_msg__pb2
from akash.proto.akash.escrow.id.v1 import id_pb2 as akash_dot_escrow_dot_id_dot_v1_dot_id__pb2
from akash.proto.akash.base.deposit.v1 import deposit_pb2 as akash_dot_base_dot_deposit_dot_v1_dot_deposit__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19\x61kash/escrow/v1/msg.proto\x12\x0f\x61kash.escrow.v1\x1a\x14gogoproto/gogo.proto\x1a\x19\x63osmos_proto/cosmos.proto\x1a\x17\x63osmos/msg/v1/msg.proto\x1a\x1b\x61kash/escrow/id/v1/id.proto\x1a#akash/base/deposit/v1/deposit.proto\"\x85\x02\n\x11MsgAccountDeposit\x12\x43\n\x06signer\x18\x01 \x01(\tB3\xea\xde\x1f\x06signer\xf2\xde\x1f\ryaml:\"signer\"\xd2\xb4-\x14\x63osmos.AddressString\x12\x46\n\x02id\x18\x02 \x01(\x0b\x32\x1b.akash.escrow.id.v1.AccountB\x1d\xc8\xde\x1f\x00\xe2\xde\x1f\x02ID\xea\xde\x1f\x02id\xf2\xde\x1f\tyaml:\"id\"\x12R\n\x07\x64\x65posit\x18\x03 \x01(\x0b\x32\x1e.akash.base.deposit.v1.DepositB!\xc8\xde\x1f\x00\xea\xde\x1f\x07\x64\x65posit\xf2\xde\x1f\x0eyaml:\"deposit\":\x0f\xe8\xa0\x1f\x00\x82\xe7\xb0*\x06signer\"\x1b\n\x19MsgAccountDepositResponseB\x1fZ\x1dpkg.akt.dev/go/node/escrow/v1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'akash.escrow.v1.msg_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\035pkg.akt.dev/go/node/escrow/v1'
  _globals['_MSGACCOUNTDEPOSIT'].fields_by_name['signer']._options = None
  _globals['_MSGACCOUNTDEPOSIT'].fields_by_name['signer']._serialized_options = b'\352\336\037\006signer\362\336\037\ryaml:\"signer\"\322\264-\024cosmos.AddressString'
  _globals['_MSGACCOUNTDEPOSIT'].fields_by_name['id']._options = None
  _globals['_MSGACCOUNTDEPOSIT'].fields_by_name['id']._serialized_options = b'\310\336\037\000\342\336\037\002ID\352\336\037\002id\362\336\037\tyaml:\"id\"'
  _globals['_MSGACCOUNTDEPOSIT'].fields_by_name['deposit']._options = None
  _globals['_MSGACCOUNTDEPOSIT'].fields_by_name['deposit']._serialized_options = b'\310\336\037\000\352\336\037\007deposit\362\336\037\016yaml:\"deposit\"'
  _globals['_MSGACCOUNTDEPOSIT']._options = None
  _globals['_MSGACCOUNTDEPOSIT']._serialized_options = b'\350\240\037\000\202\347\260*\006signer'
  _globals['_MSGACCOUNTDEPOSIT']._serialized_start=187
  _globals['_MSGACCOUNTDEPOSIT']._serialized_end=448
  _globals['_MSGACCOUNTDEPOSITRESPONSE']._serialized_start=450
  _globals['_MSGACCOUNTDEPOSITRESPONSE']._serialized_end=477
# @@protoc_insertion_point(module_scope)
