# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: akash/escrow/v1/query.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from akash.proto.gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2
from akash.proto.google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2
from akash.proto.cosmos.base.query.v1beta1 import pagination_pb2 as cosmos_dot_base_dot_query_dot_v1beta1_dot_pagination__pb2
from akash.proto.akash.escrow.types.v1 import account_pb2 as akash_dot_escrow_dot_types_dot_v1_dot_account__pb2
from akash.proto.akash.escrow.types.v1 import payment_pb2 as akash_dot_escrow_dot_types_dot_v1_dot_payment__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1b\x61kash/escrow/v1/query.proto\x12\x0f\x61kash.escrow.v1\x1a\x14gogoproto/gogo.proto\x1a\x1cgoogle/api/annotations.proto\x1a*cosmos/base/query/v1beta1/pagination.proto\x1a#akash/escrow/types/v1/account.proto\x1a#akash/escrow/types/v1/payment.proto\"\x8c\x01\n\x14QueryAccountsRequest\x12\r\n\x05state\x18\x01 \x01(\t\x12)\n\x03xid\x18\x02 \x01(\tB\x1c\xe2\xde\x1f\x03XID\xea\xde\x1f\x03xid\xf2\xde\x1f\nyaml:\"xid\"\x12:\n\npagination\x18\x05 \x01(\x0b\x32&.cosmos.base.query.v1beta1.PageRequest\"\xbc\x01\n\x15QueryAccountsResponse\x12\x66\n\x08\x61\x63\x63ounts\x18\x01 \x03(\x0b\x32\x1e.akash.escrow.types.v1.AccountB4\xc8\xde\x1f\x00\xaa\xdf\x1f,pkg.akt.dev/go/node/escrow/types/v1.Accounts\x12;\n\npagination\x18\x02 \x01(\x0b\x32\'.cosmos.base.query.v1beta1.PageResponse\"\x8c\x01\n\x14QueryPaymentsRequest\x12\r\n\x05state\x18\x01 \x01(\t\x12)\n\x03xid\x18\x02 \x01(\tB\x1c\xe2\xde\x1f\x03XID\xea\xde\x1f\x03xid\xf2\xde\x1f\nyaml:\"xid\"\x12:\n\npagination\x18\x06 \x01(\x0b\x32&.cosmos.base.query.v1beta1.PageRequest\"\xbc\x01\n\x15QueryPaymentsResponse\x12\x66\n\x08payments\x18\x01 \x03(\x0b\x32\x1e.akash.escrow.types.v1.PaymentB4\xc8\xde\x1f\x00\xaa\xdf\x1f,pkg.akt.dev/go/node/escrow/types/v1.Payments\x12;\n\npagination\x18\x02 \x01(\x0b\x32\'.cosmos.base.query.v1beta1.PageResponse2\x91\x02\n\x05Query\x12\x82\x01\n\x08\x41\x63\x63ounts\x12%.akash.escrow.v1.QueryAccountsRequest\x1a&.akash.escrow.v1.QueryAccountsResponse\"\'\x82\xd3\xe4\x93\x02!\x12\x1f/akash/escrow/v1/types/accounts\x12\x82\x01\n\x08Payments\x12%.akash.escrow.v1.QueryPaymentsRequest\x1a&.akash.escrow.v1.QueryPaymentsResponse\"\'\x82\xd3\xe4\x93\x02!\x12\x1f/akash/escrow/v1/types/paymentsB\x1fZ\x1dpkg.akt.dev/go/node/escrow/v1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'akash.escrow.v1.query_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\035pkg.akt.dev/go/node/escrow/v1'
  _globals['_QUERYACCOUNTSREQUEST'].fields_by_name['xid']._options = None
  _globals['_QUERYACCOUNTSREQUEST'].fields_by_name['xid']._serialized_options = b'\342\336\037\003XID\352\336\037\003xid\362\336\037\nyaml:\"xid\"'
  _globals['_QUERYACCOUNTSRESPONSE'].fields_by_name['accounts']._options = None
  _globals['_QUERYACCOUNTSRESPONSE'].fields_by_name['accounts']._serialized_options = b'\310\336\037\000\252\337\037,pkg.akt.dev/go/node/escrow/types/v1.Accounts'
  _globals['_QUERYPAYMENTSREQUEST'].fields_by_name['xid']._options = None
  _globals['_QUERYPAYMENTSREQUEST'].fields_by_name['xid']._serialized_options = b'\342\336\037\003XID\352\336\037\003xid\362\336\037\nyaml:\"xid\"'
  _globals['_QUERYPAYMENTSRESPONSE'].fields_by_name['payments']._options = None
  _globals['_QUERYPAYMENTSRESPONSE'].fields_by_name['payments']._serialized_options = b'\310\336\037\000\252\337\037,pkg.akt.dev/go/node/escrow/types/v1.Payments'
  _globals['_QUERY'].methods_by_name['Accounts']._options = None
  _globals['_QUERY'].methods_by_name['Accounts']._serialized_options = b'\202\323\344\223\002!\022\037/akash/escrow/v1/types/accounts'
  _globals['_QUERY'].methods_by_name['Payments']._options = None
  _globals['_QUERY'].methods_by_name['Payments']._serialized_options = b'\202\323\344\223\002!\022\037/akash/escrow/v1/types/payments'
  _globals['_QUERYACCOUNTSREQUEST']._serialized_start=219
  _globals['_QUERYACCOUNTSREQUEST']._serialized_end=359
  _globals['_QUERYACCOUNTSRESPONSE']._serialized_start=362
  _globals['_QUERYACCOUNTSRESPONSE']._serialized_end=550
  _globals['_QUERYPAYMENTSREQUEST']._serialized_start=553
  _globals['_QUERYPAYMENTSREQUEST']._serialized_end=693
  _globals['_QUERYPAYMENTSRESPONSE']._serialized_start=696
  _globals['_QUERYPAYMENTSRESPONSE']._serialized_end=884
  _globals['_QUERY']._serialized_start=887
  _globals['_QUERY']._serialized_end=1160
# @@protoc_insertion_point(module_scope)
