# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: akash/deployment/v1beta4/deploymentmsg.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from akash.proto.gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2
from akash.proto.akash.deployment.v1 import deployment_pb2 as akash_dot_deployment_dot_v1_dot_deployment__pb2
from akash.proto.akash.deployment.v1beta4 import groupspec_pb2 as akash_dot_deployment_dot_v1beta4_dot_groupspec__pb2
from akash.proto.akash.base.deposit.v1 import deposit_pb2 as akash_dot_base_dot_deposit_dot_v1_dot_deposit__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n,akash/deployment/v1beta4/deploymentmsg.proto\x12\x18\x61kash.deployment.v1beta4\x1a\x14gogoproto/gogo.proto\x1a$akash/deployment/v1/deployment.proto\x1a(akash/deployment/v1beta4/groupspec.proto\x1a#akash/base/deposit/v1/deposit.proto\"\xc8\x02\n\x13MsgCreateDeployment\x12L\n\x02id\x18\x01 \x01(\x0b\x32!.akash.deployment.v1.DeploymentIDB\x1d\xc8\xde\x1f\x00\xe2\xde\x1f\x02ID\xea\xde\x1f\x02id\xf2\xde\x1f\tyaml:\"id\"\x12\x62\n\x06groups\x18\x02 \x03(\x0b\x32#.akash.deployment.v1beta4.GroupSpecB-\xc8\xde\x1f\x00\xea\xde\x1f\x06groups\xf2\xde\x1f\ryaml:\"groups\"\xaa\xdf\x1f\nGroupSpecs\x12%\n\x04hash\x18\x03 \x01(\x0c\x42\x17\xea\xde\x1f\x04hash\xf2\xde\x1f\x0byaml:\"hash\"\x12R\n\x07\x64\x65posit\x18\x04 \x01(\x0b\x32\x1e.akash.base.deposit.v1.DepositB!\xc8\xde\x1f\x00\xea\xde\x1f\x07\x64\x65posit\xf2\xde\x1f\x0eyaml:\"deposit\":\x04\xe8\xa0\x1f\x00\"\x1d\n\x1bMsgCreateDeploymentResponse\"\x90\x01\n\x13MsgUpdateDeployment\x12L\n\x02id\x18\x01 \x01(\x0b\x32!.akash.deployment.v1.DeploymentIDB\x1d\xc8\xde\x1f\x00\xe2\xde\x1f\x02ID\xea\xde\x1f\x02id\xf2\xde\x1f\tyaml:\"id\"\x12%\n\x04hash\x18\x03 \x01(\x0c\x42\x17\xea\xde\x1f\x04hash\xf2\xde\x1f\x0byaml:\"hash\":\x04\xe8\xa0\x1f\x00\"\x1d\n\x1bMsgUpdateDeploymentResponse\"h\n\x12MsgCloseDeployment\x12L\n\x02id\x18\x01 \x01(\x0b\x32!.akash.deployment.v1.DeploymentIDB\x1d\xc8\xde\x1f\x00\xe2\xde\x1f\x02ID\xea\xde\x1f\x02id\xf2\xde\x1f\tyaml:\"id\":\x04\xe8\xa0\x1f\x00\"\x1c\n\x1aMsgCloseDeploymentResponseB(Z&pkg.akt.dev/go/node/deployment/v1beta4b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'akash.deployment.v1beta4.deploymentmsg_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z&pkg.akt.dev/go/node/deployment/v1beta4'
  _globals['_MSGCREATEDEPLOYMENT'].fields_by_name['id']._options = None
  _globals['_MSGCREATEDEPLOYMENT'].fields_by_name['id']._serialized_options = b'\310\336\037\000\342\336\037\002ID\352\336\037\002id\362\336\037\tyaml:\"id\"'
  _globals['_MSGCREATEDEPLOYMENT'].fields_by_name['groups']._options = None
  _globals['_MSGCREATEDEPLOYMENT'].fields_by_name['groups']._serialized_options = b'\310\336\037\000\352\336\037\006groups\362\336\037\ryaml:\"groups\"\252\337\037\nGroupSpecs'
  _globals['_MSGCREATEDEPLOYMENT'].fields_by_name['hash']._options = None
  _globals['_MSGCREATEDEPLOYMENT'].fields_by_name['hash']._serialized_options = b'\352\336\037\004hash\362\336\037\013yaml:\"hash\"'
  _globals['_MSGCREATEDEPLOYMENT'].fields_by_name['deposit']._options = None
  _globals['_MSGCREATEDEPLOYMENT'].fields_by_name['deposit']._serialized_options = b'\310\336\037\000\352\336\037\007deposit\362\336\037\016yaml:\"deposit\"'
  _globals['_MSGCREATEDEPLOYMENT']._options = None
  _globals['_MSGCREATEDEPLOYMENT']._serialized_options = b'\350\240\037\000'
  _globals['_MSGUPDATEDEPLOYMENT'].fields_by_name['id']._options = None
  _globals['_MSGUPDATEDEPLOYMENT'].fields_by_name['id']._serialized_options = b'\310\336\037\000\342\336\037\002ID\352\336\037\002id\362\336\037\tyaml:\"id\"'
  _globals['_MSGUPDATEDEPLOYMENT'].fields_by_name['hash']._options = None
  _globals['_MSGUPDATEDEPLOYMENT'].fields_by_name['hash']._serialized_options = b'\352\336\037\004hash\362\336\037\013yaml:\"hash\"'
  _globals['_MSGUPDATEDEPLOYMENT']._options = None
  _globals['_MSGUPDATEDEPLOYMENT']._serialized_options = b'\350\240\037\000'
  _globals['_MSGCLOSEDEPLOYMENT'].fields_by_name['id']._options = None
  _globals['_MSGCLOSEDEPLOYMENT'].fields_by_name['id']._serialized_options = b'\310\336\037\000\342\336\037\002ID\352\336\037\002id\362\336\037\tyaml:\"id\"'
  _globals['_MSGCLOSEDEPLOYMENT']._options = None
  _globals['_MSGCLOSEDEPLOYMENT']._serialized_options = b'\350\240\037\000'
  _globals['_MSGCREATEDEPLOYMENT']._serialized_start=214
  _globals['_MSGCREATEDEPLOYMENT']._serialized_end=542
  _globals['_MSGCREATEDEPLOYMENTRESPONSE']._serialized_start=544
  _globals['_MSGCREATEDEPLOYMENTRESPONSE']._serialized_end=573
  _globals['_MSGUPDATEDEPLOYMENT']._serialized_start=576
  _globals['_MSGUPDATEDEPLOYMENT']._serialized_end=720
  _globals['_MSGUPDATEDEPLOYMENTRESPONSE']._serialized_start=722
  _globals['_MSGUPDATEDEPLOYMENTRESPONSE']._serialized_end=751
  _globals['_MSGCLOSEDEPLOYMENT']._serialized_start=753
  _globals['_MSGCLOSEDEPLOYMENT']._serialized_end=857
  _globals['_MSGCLOSEDEPLOYMENTRESPONSE']._serialized_start=859
  _globals['_MSGCLOSEDEPLOYMENTRESPONSE']._serialized_end=887
# @@protoc_insertion_point(module_scope)
