# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: akash/deployment/v1beta4/filters.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from akash.proto.gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2
from akash.proto.cosmos_proto import cosmos_pb2 as cosmos__proto_dot_cosmos__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&akash/deployment/v1beta4/filters.proto\x12\x18\x61kash.deployment.v1beta4\x1a\x14gogoproto/gogo.proto\x1a\x19\x63osmos_proto/cosmos.proto\"\xb4\x01\n\x11\x44\x65ploymentFilters\x12@\n\x05owner\x18\x01 \x01(\tB1\xea\xde\x1f\x05owner\xf2\xde\x1f\x0cyaml:\"owner\"\xd2\xb4-\x14\x63osmos.AddressString\x12-\n\x04\x64seq\x18\x02 \x01(\x04\x42\x1f\xe2\xde\x1f\x04\x44Seq\xea\xde\x1f\x04\x64seq\xf2\xde\x1f\x0byaml:\"dseq\"\x12(\n\x05state\x18\x03 \x01(\tB\x19\xea\xde\x1f\x05state\xf2\xde\x1f\x0cyaml:\"state\":\x04\xe8\xa0\x1f\x00\"\xde\x01\n\x0cGroupFilters\x12@\n\x05owner\x18\x01 \x01(\tB1\xea\xde\x1f\x05owner\xf2\xde\x1f\x0cyaml:\"owner\"\xd2\xb4-\x14\x63osmos.AddressString\x12-\n\x04\x64seq\x18\x02 \x01(\x04\x42\x1f\xe2\xde\x1f\x04\x44Seq\xea\xde\x1f\x04\x64seq\xf2\xde\x1f\x0byaml:\"dseq\"\x12-\n\x04gseq\x18\x03 \x01(\x04\x42\x1f\xe2\xde\x1f\x04GSeq\xea\xde\x1f\x04gseq\xf2\xde\x1f\x0byaml:\"gseq\"\x12(\n\x05state\x18\x04 \x01(\tB\x19\xea\xde\x1f\x05state\xf2\xde\x1f\x0cyaml:\"state\":\x04\xe8\xa0\x1f\x00\x42(Z&pkg.akt.dev/go/node/deployment/v1beta4b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'akash.deployment.v1beta4.filters_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z&pkg.akt.dev/go/node/deployment/v1beta4'
  _globals['_DEPLOYMENTFILTERS'].fields_by_name['owner']._options = None
  _globals['_DEPLOYMENTFILTERS'].fields_by_name['owner']._serialized_options = b'\352\336\037\005owner\362\336\037\014yaml:\"owner\"\322\264-\024cosmos.AddressString'
  _globals['_DEPLOYMENTFILTERS'].fields_by_name['dseq']._options = None
  _globals['_DEPLOYMENTFILTERS'].fields_by_name['dseq']._serialized_options = b'\342\336\037\004DSeq\352\336\037\004dseq\362\336\037\013yaml:\"dseq\"'
  _globals['_DEPLOYMENTFILTERS'].fields_by_name['state']._options = None
  _globals['_DEPLOYMENTFILTERS'].fields_by_name['state']._serialized_options = b'\352\336\037\005state\362\336\037\014yaml:\"state\"'
  _globals['_DEPLOYMENTFILTERS']._options = None
  _globals['_DEPLOYMENTFILTERS']._serialized_options = b'\350\240\037\000'
  _globals['_GROUPFILTERS'].fields_by_name['owner']._options = None
  _globals['_GROUPFILTERS'].fields_by_name['owner']._serialized_options = b'\352\336\037\005owner\362\336\037\014yaml:\"owner\"\322\264-\024cosmos.AddressString'
  _globals['_GROUPFILTERS'].fields_by_name['dseq']._options = None
  _globals['_GROUPFILTERS'].fields_by_name['dseq']._serialized_options = b'\342\336\037\004DSeq\352\336\037\004dseq\362\336\037\013yaml:\"dseq\"'
  _globals['_GROUPFILTERS'].fields_by_name['gseq']._options = None
  _globals['_GROUPFILTERS'].fields_by_name['gseq']._serialized_options = b'\342\336\037\004GSeq\352\336\037\004gseq\362\336\037\013yaml:\"gseq\"'
  _globals['_GROUPFILTERS'].fields_by_name['state']._options = None
  _globals['_GROUPFILTERS'].fields_by_name['state']._serialized_options = b'\352\336\037\005state\362\336\037\014yaml:\"state\"'
  _globals['_GROUPFILTERS']._options = None
  _globals['_GROUPFILTERS']._serialized_options = b'\350\240\037\000'
  _globals['_DEPLOYMENTFILTERS']._serialized_start=118
  _globals['_DEPLOYMENTFILTERS']._serialized_end=298
  _globals['_GROUPFILTERS']._serialized_start=301
  _globals['_GROUPFILTERS']._serialized_end=523
# @@protoc_insertion_point(module_scope)
