# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: akash/deployment/v1beta4/groupmsg.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from akash.proto.gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2
from akash.proto.akash.deployment.v1 import group_pb2 as akash_dot_deployment_dot_v1_dot_group__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\'akash/deployment/v1beta4/groupmsg.proto\x12\x18\x61kash.deployment.v1beta4\x1a\x14gogoproto/gogo.proto\x1a\x1f\x61kash/deployment/v1/group.proto\"^\n\rMsgCloseGroup\x12G\n\x02id\x18\x01 \x01(\x0b\x32\x1c.akash.deployment.v1.GroupIDB\x1d\xc8\xde\x1f\x00\xe2\xde\x1f\x02ID\xea\xde\x1f\x02id\xf2\xde\x1f\tyaml:\"id\":\x04\xe8\xa0\x1f\x00\"\x17\n\x15MsgCloseGroupResponse\"^\n\rMsgPauseGroup\x12G\n\x02id\x18\x01 \x01(\x0b\x32\x1c.akash.deployment.v1.GroupIDB\x1d\xc8\xde\x1f\x00\xe2\xde\x1f\x02ID\xea\xde\x1f\x02id\xf2\xde\x1f\tyaml:\"id\":\x04\xe8\xa0\x1f\x00\"\x17\n\x15MsgPauseGroupResponse\"^\n\rMsgStartGroup\x12G\n\x02id\x18\x01 \x01(\x0b\x32\x1c.akash.deployment.v1.GroupIDB\x1d\xc8\xde\x1f\x00\xe2\xde\x1f\x02ID\xea\xde\x1f\x02id\xf2\xde\x1f\tyaml:\"id\":\x04\xe8\xa0\x1f\x00\"\x17\n\x15MsgStartGroupResponseB(Z&pkg.akt.dev/go/node/deployment/v1beta4b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'akash.deployment.v1beta4.groupmsg_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z&pkg.akt.dev/go/node/deployment/v1beta4'
  _globals['_MSGCLOSEGROUP'].fields_by_name['id']._options = None
  _globals['_MSGCLOSEGROUP'].fields_by_name['id']._serialized_options = b'\310\336\037\000\342\336\037\002ID\352\336\037\002id\362\336\037\tyaml:\"id\"'
  _globals['_MSGCLOSEGROUP']._options = None
  _globals['_MSGCLOSEGROUP']._serialized_options = b'\350\240\037\000'
  _globals['_MSGPAUSEGROUP'].fields_by_name['id']._options = None
  _globals['_MSGPAUSEGROUP'].fields_by_name['id']._serialized_options = b'\310\336\037\000\342\336\037\002ID\352\336\037\002id\362\336\037\tyaml:\"id\"'
  _globals['_MSGPAUSEGROUP']._options = None
  _globals['_MSGPAUSEGROUP']._serialized_options = b'\350\240\037\000'
  _globals['_MSGSTARTGROUP'].fields_by_name['id']._options = None
  _globals['_MSGSTARTGROUP'].fields_by_name['id']._serialized_options = b'\310\336\037\000\342\336\037\002ID\352\336\037\002id\362\336\037\tyaml:\"id\"'
  _globals['_MSGSTARTGROUP']._options = None
  _globals['_MSGSTARTGROUP']._serialized_options = b'\350\240\037\000'
  _globals['_MSGCLOSEGROUP']._serialized_start=124
  _globals['_MSGCLOSEGROUP']._serialized_end=218
  _globals['_MSGCLOSEGROUPRESPONSE']._serialized_start=220
  _globals['_MSGCLOSEGROUPRESPONSE']._serialized_end=243
  _globals['_MSGPAUSEGROUP']._serialized_start=245
  _globals['_MSGPAUSEGROUP']._serialized_end=339
  _globals['_MSGPAUSEGROUPRESPONSE']._serialized_start=341
  _globals['_MSGPAUSEGROUPRESPONSE']._serialized_end=364
  _globals['_MSGSTARTGROUP']._serialized_start=366
  _globals['_MSGSTARTGROUP']._serialized_end=460
  _globals['_MSGSTARTGROUPRESPONSE']._serialized_start=462
  _globals['_MSGSTARTGROUPRESPONSE']._serialized_end=485
# @@protoc_insertion_point(module_scope)
