# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: akash/deployment/v1beta4/service.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from akash.proto.akash.deployment.v1beta4 import deploymentmsg_pb2 as akash_dot_deployment_dot_v1beta4_dot_deploymentmsg__pb2
from akash.proto.akash.deployment.v1beta4 import groupmsg_pb2 as akash_dot_deployment_dot_v1beta4_dot_groupmsg__pb2
from akash.proto.akash.deployment.v1beta4 import paramsmsg_pb2 as akash_dot_deployment_dot_v1beta4_dot_paramsmsg__pb2
from akash.proto.cosmos.msg.v1 import msg_pb2 as cosmos_dot_msg_dot_v1_dot_msg__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&akash/deployment/v1beta4/service.proto\x12\x18\x61kash.deployment.v1beta4\x1a,akash/deployment/v1beta4/deploymentmsg.proto\x1a\'akash/deployment/v1beta4/groupmsg.proto\x1a(akash/deployment/v1beta4/paramsmsg.proto\x1a\x17\x63osmos/msg/v1/msg.proto2\x9d\x06\n\x03Msg\x12x\n\x10\x43reateDeployment\x12-.akash.deployment.v1beta4.MsgCreateDeployment\x1a\x35.akash.deployment.v1beta4.MsgCreateDeploymentResponse\x12x\n\x10UpdateDeployment\x12-.akash.deployment.v1beta4.MsgUpdateDeployment\x1a\x35.akash.deployment.v1beta4.MsgUpdateDeploymentResponse\x12u\n\x0f\x43loseDeployment\x12,.akash.deployment.v1beta4.MsgCloseDeployment\x1a\x34.akash.deployment.v1beta4.MsgCloseDeploymentResponse\x12\x66\n\nCloseGroup\x12\'.akash.deployment.v1beta4.MsgCloseGroup\x1a/.akash.deployment.v1beta4.MsgCloseGroupResponse\x12\x66\n\nPauseGroup\x12\'.akash.deployment.v1beta4.MsgPauseGroup\x1a/.akash.deployment.v1beta4.MsgPauseGroupResponse\x12\x66\n\nStartGroup\x12\'.akash.deployment.v1beta4.MsgStartGroup\x1a/.akash.deployment.v1beta4.MsgStartGroupResponse\x12l\n\x0cUpdateParams\x12).akash.deployment.v1beta4.MsgUpdateParams\x1a\x31.akash.deployment.v1beta4.MsgUpdateParamsResponse\x1a\x05\x80\xe7\xb0*\x01\x42(Z&pkg.akt.dev/go/node/deployment/v1beta4b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'akash.deployment.v1beta4.service_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z&pkg.akt.dev/go/node/deployment/v1beta4'
  _globals['_MSG']._options = None
  _globals['_MSG']._serialized_options = b'\200\347\260*\001'
  _globals['_MSG']._serialized_start=223
  _globals['_MSG']._serialized_end=1020
# @@protoc_insertion_point(module_scope)
