# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: akash/cert/v1/cert.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from akash.proto.gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2
from akash.proto.cosmos_proto import cosmos_pb2 as cosmos__proto_dot_cosmos__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18\x61kash/cert/v1/cert.proto\x12\rakash.cert.v1\x1a\x14gogoproto/gogo.proto\x1a\x19\x63osmos_proto/cosmos.proto\"}\n\x02ID\x12@\n\x05owner\x18\x01 \x01(\tB1\xea\xde\x1f\x05owner\xf2\xde\x1f\x0cyaml:\"owner\"\xd2\xb4-\x14\x63osmos.AddressString\x12+\n\x06serial\x18\x02 \x01(\tB\x1b\xea\xde\x1f\x06serial\xf2\xde\x1f\ryaml:\"serial\":\x08\x98\xa0\x1f\x00\xe8\xa0\x1f\x00\"\xa1\x01\n\x0b\x43\x65rtificate\x12>\n\x05state\x18\x02 \x01(\x0e\x32\x14.akash.cert.v1.StateB\x19\xea\xde\x1f\x05state\xf2\xde\x1f\x0cyaml:\"state\"\x12%\n\x04\x63\x65rt\x18\x03 \x01(\x0c\x42\x17\xea\xde\x1f\x04\x63\x65rt\xf2\xde\x1f\x0byaml:\"cert\"\x12+\n\x06pubkey\x18\x04 \x01(\x0c\x42\x1b\xea\xde\x1f\x06pubkey\xf2\xde\x1f\ryaml:\"pubkey\"*}\n\x05State\x12(\n\x07invalid\x10\x00\x1a\x1b\x8a\x9d \x17\x43\x65rtificateStateInvalid\x12\x1f\n\x05valid\x10\x01\x1a\x14\x8a\x9d \x10\x43\x65rtificateValid\x12#\n\x07revoked\x10\x02\x1a\x16\x8a\x9d \x12\x43\x65rtificateRevoked\x1a\x04\x88\xa3\x1e\x00\x42\x1dZ\x1bpkg.akt.dev/go/node/cert/v1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'akash.cert.v1.cert_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\033pkg.akt.dev/go/node/cert/v1'
  _globals['_STATE']._options = None
  _globals['_STATE']._serialized_options = b'\210\243\036\000'
  _globals['_STATE'].values_by_name["invalid"]._options = None
  _globals['_STATE'].values_by_name["invalid"]._serialized_options = b'\212\235 \027CertificateStateInvalid'
  _globals['_STATE'].values_by_name["valid"]._options = None
  _globals['_STATE'].values_by_name["valid"]._serialized_options = b'\212\235 \020CertificateValid'
  _globals['_STATE'].values_by_name["revoked"]._options = None
  _globals['_STATE'].values_by_name["revoked"]._serialized_options = b'\212\235 \022CertificateRevoked'
  _globals['_ID'].fields_by_name['owner']._options = None
  _globals['_ID'].fields_by_name['owner']._serialized_options = b'\352\336\037\005owner\362\336\037\014yaml:\"owner\"\322\264-\024cosmos.AddressString'
  _globals['_ID'].fields_by_name['serial']._options = None
  _globals['_ID'].fields_by_name['serial']._serialized_options = b'\352\336\037\006serial\362\336\037\ryaml:\"serial\"'
  _globals['_ID']._options = None
  _globals['_ID']._serialized_options = b'\230\240\037\000\350\240\037\000'
  _globals['_CERTIFICATE'].fields_by_name['state']._options = None
  _globals['_CERTIFICATE'].fields_by_name['state']._serialized_options = b'\352\336\037\005state\362\336\037\014yaml:\"state\"'
  _globals['_CERTIFICATE'].fields_by_name['cert']._options = None
  _globals['_CERTIFICATE'].fields_by_name['cert']._serialized_options = b'\352\336\037\004cert\362\336\037\013yaml:\"cert\"'
  _globals['_CERTIFICATE'].fields_by_name['pubkey']._options = None
  _globals['_CERTIFICATE'].fields_by_name['pubkey']._serialized_options = b'\352\336\037\006pubkey\362\336\037\ryaml:\"pubkey\"'
  _globals['_STATE']._serialized_start=383
  _globals['_STATE']._serialized_end=508
  _globals['_ID']._serialized_start=92
  _globals['_ID']._serialized_end=217
  _globals['_CERTIFICATE']._serialized_start=220
  _globals['_CERTIFICATE']._serialized_end=381
# @@protoc_insertion_point(module_scope)
