# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: akash/cert/v1/genesis.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from akash.proto.gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2
from akash.proto.cosmos_proto import cosmos_pb2 as cosmos__proto_dot_cosmos__pb2
from akash.proto.akash.cert.v1 import cert_pb2 as akash_dot_cert_dot_v1_dot_cert__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1b\x61kash/cert/v1/genesis.proto\x12\rakash.cert.v1\x1a\x14gogoproto/gogo.proto\x1a\x19\x63osmos_proto/cosmos.proto\x1a\x18\x61kash/cert/v1/cert.proto\"\xb2\x01\n\x12GenesisCertificate\x12@\n\x05owner\x18\x01 \x01(\tB1\xea\xde\x1f\x05owner\xf2\xde\x1f\x0cyaml:\"owner\"\xd2\xb4-\x14\x63osmos.AddressString\x12Z\n\x0b\x63\x65rtificate\x18\x02 \x01(\x0b\x32\x1a.akash.cert.v1.CertificateB)\xc8\xde\x1f\x00\xea\xde\x1f\x0b\x63\x65rtificate\xf2\xde\x1f\x12yaml:\"certificate\"\"\x8b\x01\n\x0cGenesisState\x12{\n\x0c\x63\x65rtificates\x18\x01 \x03(\x0b\x32!.akash.cert.v1.GenesisCertificateBB\xc8\xde\x1f\x00\xea\xde\x1f\x0c\x63\x65rtificates\xf2\xde\x1f\x13yaml:\"certificates\"\xaa\xdf\x1f\x13GenesisCertificatesB\x1dZ\x1bpkg.akt.dev/go/node/cert/v1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'akash.cert.v1.genesis_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\033pkg.akt.dev/go/node/cert/v1'
  _globals['_GENESISCERTIFICATE'].fields_by_name['owner']._options = None
  _globals['_GENESISCERTIFICATE'].fields_by_name['owner']._serialized_options = b'\352\336\037\005owner\362\336\037\014yaml:\"owner\"\322\264-\024cosmos.AddressString'
  _globals['_GENESISCERTIFICATE'].fields_by_name['certificate']._options = None
  _globals['_GENESISCERTIFICATE'].fields_by_name['certificate']._serialized_options = b'\310\336\037\000\352\336\037\013certificate\362\336\037\022yaml:\"certificate\"'
  _globals['_GENESISSTATE'].fields_by_name['certificates']._options = None
  _globals['_GENESISSTATE'].fields_by_name['certificates']._serialized_options = b'\310\336\037\000\352\336\037\014certificates\362\336\037\023yaml:\"certificates\"\252\337\037\023GenesisCertificates'
  _globals['_GENESISCERTIFICATE']._serialized_start=122
  _globals['_GENESISCERTIFICATE']._serialized_end=300
  _globals['_GENESISSTATE']._serialized_start=303
  _globals['_GENESISSTATE']._serialized_end=442
# @@protoc_insertion_point(module_scope)
