# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: akash/cert/v1/msg.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from akash.proto.gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2
from akash.proto.cosmos_proto import cosmos_pb2 as cosmos__proto_dot_cosmos__pb2
from akash.proto.cosmos.msg.v1 import msg_pb2 as cosmos_dot_msg_dot_v1_dot_msg__pb2
from akash.proto.akash.cert.v1 import cert_pb2 as akash_dot_cert_dot_v1_dot_cert__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17\x61kash/cert/v1/msg.proto\x12\rakash.cert.v1\x1a\x14gogoproto/gogo.proto\x1a\x19\x63osmos_proto/cosmos.proto\x1a\x17\x63osmos/msg/v1/msg.proto\x1a\x18\x61kash/cert/v1/cert.proto\"\xbc\x01\n\x14MsgCreateCertificate\x12@\n\x05owner\x18\x01 \x01(\tB1\xea\xde\x1f\x05owner\xf2\xde\x1f\x0cyaml:\"owner\"\xd2\xb4-\x14\x63osmos.AddressString\x12%\n\x04\x63\x65rt\x18\x02 \x01(\x0c\x42\x17\xea\xde\x1f\x04\x63\x65rt\xf2\xde\x1f\x0byaml:\"cert\"\x12+\n\x06pubkey\x18\x03 \x01(\x0c\x42\x1b\xea\xde\x1f\x06pubkey\xf2\xde\x1f\ryaml:\"pubkey\":\x0e\xe8\xa0\x1f\x00\x82\xe7\xb0*\x05owner\"\x1e\n\x1cMsgCreateCertificateResponse\"Z\n\x14MsgRevokeCertificate\x12<\n\x02id\x18\x01 \x01(\x0b\x32\x11.akash.cert.v1.IDB\x1d\xc8\xde\x1f\x00\xe2\xde\x1f\x02ID\xea\xde\x1f\x02id\xf2\xde\x1f\tyaml:\"id\":\x04\xe8\xa0\x1f\x00\"\x1e\n\x1cMsgRevokeCertificateResponseB\x1dZ\x1bpkg.akt.dev/go/node/cert/v1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'akash.cert.v1.msg_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\033pkg.akt.dev/go/node/cert/v1'
  _globals['_MSGCREATECERTIFICATE'].fields_by_name['owner']._options = None
  _globals['_MSGCREATECERTIFICATE'].fields_by_name['owner']._serialized_options = b'\352\336\037\005owner\362\336\037\014yaml:\"owner\"\322\264-\024cosmos.AddressString'
  _globals['_MSGCREATECERTIFICATE'].fields_by_name['cert']._options = None
  _globals['_MSGCREATECERTIFICATE'].fields_by_name['cert']._serialized_options = b'\352\336\037\004cert\362\336\037\013yaml:\"cert\"'
  _globals['_MSGCREATECERTIFICATE'].fields_by_name['pubkey']._options = None
  _globals['_MSGCREATECERTIFICATE'].fields_by_name['pubkey']._serialized_options = b'\352\336\037\006pubkey\362\336\037\ryaml:\"pubkey\"'
  _globals['_MSGCREATECERTIFICATE']._options = None
  _globals['_MSGCREATECERTIFICATE']._serialized_options = b'\350\240\037\000\202\347\260*\005owner'
  _globals['_MSGREVOKECERTIFICATE'].fields_by_name['id']._options = None
  _globals['_MSGREVOKECERTIFICATE'].fields_by_name['id']._serialized_options = b'\310\336\037\000\342\336\037\002ID\352\336\037\002id\362\336\037\tyaml:\"id\"'
  _globals['_MSGREVOKECERTIFICATE']._options = None
  _globals['_MSGREVOKECERTIFICATE']._serialized_options = b'\350\240\037\000'
  _globals['_MSGCREATECERTIFICATE']._serialized_start=143
  _globals['_MSGCREATECERTIFICATE']._serialized_end=331
  _globals['_MSGCREATECERTIFICATERESPONSE']._serialized_start=333
  _globals['_MSGCREATECERTIFICATERESPONSE']._serialized_end=363
  _globals['_MSGREVOKECERTIFICATE']._serialized_start=365
  _globals['_MSGREVOKECERTIFICATE']._serialized_end=455
  _globals['_MSGREVOKECERTIFICATERESPONSE']._serialized_start=457
  _globals['_MSGREVOKECERTIFICATERESPONSE']._serialized_end=487
# @@protoc_insertion_point(module_scope)
