# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: akash/cert/v1/service.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from akash.proto.cosmos.msg.v1 import msg_pb2 as cosmos_dot_msg_dot_v1_dot_msg__pb2
from akash.proto.akash.cert.v1 import msg_pb2 as akash_dot_cert_dot_v1_dot_msg__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1b\x61kash/cert/v1/service.proto\x12\rakash.cert.v1\x1a\x17\x63osmos/msg/v1/msg.proto\x1a\x17\x61kash/cert/v1/msg.proto2\xda\x01\n\x03Msg\x12\x65\n\x11\x43reateCertificate\x12#.akash.cert.v1.MsgCreateCertificate\x1a+.akash.cert.v1.MsgCreateCertificateResponse\x12\x65\n\x11RevokeCertificate\x12#.akash.cert.v1.MsgRevokeCertificate\x1a+.akash.cert.v1.MsgRevokeCertificateResponse\x1a\x05\x80\xe7\xb0*\x01\x42\x1dZ\x1bpkg.akt.dev/go/node/cert/v1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'akash.cert.v1.service_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\033pkg.akt.dev/go/node/cert/v1'
  _globals['_MSG']._options = None
  _globals['_MSG']._serialized_options = b'\200\347\260*\001'
  _globals['_MSG']._serialized_start=97
  _globals['_MSG']._serialized_end=315
# @@protoc_insertion_point(module_scope)
