# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: akash/discovery/v1/akash.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from akash.proto.akash.discovery.v1 import client_info_pb2 as akash_dot_discovery_dot_v1_dot_client__info__pb2
from akash.proto.gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1e\x61kash/discovery/v1/akash.proto\x12\x12\x61kash.discovery.v1\x1a$akash/discovery/v1/client_info.proto\x1a\x14gogoproto/gogo.proto\"u\n\x05\x41kash\x12l\n\x0b\x63lient_info\x18\x01 \x01(\x0b\x32\x1e.akash.discovery.v1.ClientInfoB7\xc8\xde\x1f\x00\xe2\xde\x1f\nClientInfo\xea\xde\x1f\x0b\x63lient_info\xf2\xde\x1f\x12yaml:\"client_info\"B\x1cZ\x1apkg.akt.dev/go/node/clientb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'akash.discovery.v1.akash_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\032pkg.akt.dev/go/node/client'
  _globals['_AKASH'].fields_by_name['client_info']._options = None
  _globals['_AKASH'].fields_by_name['client_info']._serialized_options = b'\310\336\037\000\342\336\037\nClientInfo\352\336\037\013client_info\362\336\037\022yaml:\"client_info\"'
  _globals['_AKASH']._serialized_start=114
  _globals['_AKASH']._serialized_end=231
# @@protoc_insertion_point(module_scope)
